swaggerのAPIDocの追加(途中)
traPtitech/traQ pull request #1
Opened 2017-11-03 09:55 UTC by tohutohu

2017-11-04 23:58 UTC, kaz requested changes

2017-11-04 23:58 UTC, kaz commented on swagger/swagger.yaml
> +  /channels/{channelId}:
パスに変数が入ってるAPIについて、`parameters`に説明が欲しいです

`parameters[i].in = "path"`が正しいんですが、https://editor.swagger.io/ が若干古い？のでエラーになっちゃいますが、とりあえずエラー無視で

2017-11-04 23:58 UTC, kaz commented on swagger/swagger.yaml
> +  /stamps:
全部のAPIに`tags`を指定してほしいです
ココ以外でも、tagsがないところがあります

2017-11-04 23:58 UTC, kaz commented on swagger/swagger.yaml
> +        "400":
これは意味的に404かな？

2017-11-04 23:58 UTC, kaz commented on swagger/swagger.yaml
> +  /users/{id}/tags:
パラメータ名に揺れが……
`userId`に統一しましょう

2017-11-12 23:50 UTC, kaz requested changes
全体的な話ですが、ID系は全部IntegerじゃなくてUUID（つまりstring）にしましょう！

2017-11-12 23:50 UTC, kaz commented on swagger/swagger.yaml
> +      description: チャンネルにメッセージを投稿します。
メッセージ投稿がこのAPIなのは変かも？
取得が`GET /channels/{channelId}/messages`だし、`POST /channels/{channelId}/messages`になるべき

2017-11-12 23:50 UTC, kaz commented on swagger/swagger.yaml
> +      tags:
visibility関係、`/channels/{channelId}/notifications`と同じ形にして、他人の可視状態もいじれる感じにしてしまうのはどうでしょうか。

2017-11-12 23:50 UTC, kaz commented on swagger/swagger.yaml
> +      tags:
あとタグをchannelじゃなくて、独立させたほうが見やすいかな

2017-11-12 23:50 UTC, kaz commented on swagger/swagger.yaml
> +        - channel
タグをchannelじゃなくて、独立させたほうが見やすい

2017-11-12 23:50 UTC, kaz commented on swagger/swagger.yaml
> +        - message
`/users/me/unread`が良いかも。
あと、タグをmessageから独立させましょう

2017-11-12 23:50 UTC, kaz commented on swagger/swagger.yaml
> +    post:
GETがない
Message系のAPIにembedさせるにしても、一応作っておきたい

2017-11-12 23:50 UTC, kaz commented on swagger/swagger.yaml
> +      tags:
PUTよりPOSTかなぁ
あまり**編集**してるカンジがないので？

2017-11-12 23:50 UTC, kaz commented on swagger/swagger.yaml
> +    put:
`/channels`下に置くのが妥当だと感じました。
あとfixationってなんかびみょうかな〜って思ったので、`/channels/{channelId}/pin`とかはどうですか。

あと、PUTよりかはPOSTだと思う。

それと、GETが欲しいです

と、タグを分けてほしい

2017-11-13 02:54 UTC, wtks commented
mysqlでのUUIDの格納はBINARY(16)を使うでいいですか？

2017-11-13 04:17 UTC, kaz commented
文字列として格納おいた方がラクなので、`xxxxxxxx-xxxx-xxxx-Nxxx-xxxxxxxxxxxx`形式で`char(36)`かな

2017-11-13 09:01 UTC, wtks commented
DBスキーマの方は #5 で書いてます

2017-11-27 10:01 UTC, kaz approved these changes

2017-11-27 10:02 UTC, kaz commented
とりあえずいいと思います。
あとは作りながら適宜修正していきましょう。

マージしてください！

2017-11-27 10:02 UTC, merged