FileのAPIの実装
traPtitech/traQ pull request #104
Opened 2018-02-19 16:02 UTC by masutech16

#18 のサムネイルの実装以外を行いました。
やったこととかを適当にまとめておきます。

## lintに注意された点の修正
作業中にlintがいろいろ吐いてくるので内容を変えないで修正しました

## swaggerの追記
+ file関係のAPIを追記しました
+ 細かいところは独断で決めたので意見があればほしいです

## model
+ interfaceとしてFileWriterとFileReaderを定義しました
+ mimeには拡張子らしきものが入っています
+ 作業環境では`./resources`以下にファイルを格納するようにしました

## router
+ PostFileのテストコードが通らないです。お手上げなのでとりあえずpushしました
+ ファイルを送るときのContent-Typeがすべて`application/octet-stream`になるようになってます

ファイル本体関係の関数が結構不安です。
明日も時間を見つけてやろうと思いますが、何かあればコメントください。

2018-02-19 18:01 UTC, wtks requested changes

2018-02-19 18:01 UTC, wtks commented on router/files.go
> +	return c.NoContent(http.StatusCreated)
投稿されたファイルのファイルIDを返してください(swaggerの方も同様に修正)

2018-02-19 18:01 UTC, wtks commented on model/files.go
> +	ReadByID(string) ([]byte, error)
[]byteを返すってことになると、例えば数百MBの動画ファイルとかを返すときに、その動画ファイルをまるまるメモリに載せちゃってメモリ不足になるかもしれないので、ファイルのストリームを返すといいと思います。

2018-02-19 18:12 UTC, tohutohu commented
https://golang.org/pkg/mime/
こういうのでmimeタイプわかりませんか(これ使う以上の制度はいらんとおもう)

responseのヘッダーが全部オクテットストリームの理由は

2018-02-20 05:44 UTC, masutech16 commented on router/files.go
> +	return c.NoContent(http.StatusCreated)
今getで投げているデータを返すのとIDだけだとどっちがいいですかね
とりあえずgetで投げているメタデータを出すようにします

2018-02-20 05:47 UTC, wtks commented on router/files.go
> +	return c.NoContent(http.StatusCreated)
メタデータ丸ごと返してもいいと思います。

2018-02-20 05:50 UTC, masutech16 commented
Swaggerのほうに合わせてたのと、特に不都合がある気がしなかったためですね >mime-type変えてない件
Swaggerを変更したので対応したもので返すようにします

2018-02-20 07:04 UTC, masutech16 commented
postのテストが通らなかったのはboundaryが設定されていないためでした。解決しました。
テストはローカルだと通るのですが、CircleCI上だとファイルの権限がなくて死んでしまうみたいです。

2018-02-20 07:32 UTC, tohutohu commented
テスト開始前にcircleciのスクリプトかutil_testのテスト開始前のところで権限変更して書き込み権限を与えてもダメですかね

2018-02-20 08:17 UTC, kaz requested changes
routerが`main.go`で登録されていない

2018-02-20 08:17 UTC, kaz commented on docs/swagger.yaml
> +  /file:
複数形に統一されていたのでは

2018-02-20 08:17 UTC, kaz commented on model/files.go
> +		if err = os.Mkdir(dirName, 0666); err != nil {
ディレクトリは、**`x`ビットが立っていないとアクセスができません**
`0700`が良いと思います。

2018-02-20 08:17 UTC, kaz commented on model/files.go
> +// WriteByID /img/nameにデータを書き込みます
ここのコメントの意味がわからなかった

2018-02-20 08:19 UTC, kaz commented on model/files.go
> +		if err = os.Mkdir(dirName, 0666); err != nil {
CIが落ちるのはこれが原因な気がします

2018-02-20 12:43 UTC, masutech16 commented
コメントもらったところを直したところ無事動きました！　ありがとうございます！

2018-02-21 09:09 UTC, kaz approved these changes

2018-02-21 09:14 UTC, wtks approved these changes

2018-02-21 09:27 UTC, merged