#845 メッセージ引用通知
traPtitech/traQ pull request #1099
Opened 2021-03-01 15:50 UTC by hijiki51

ひとまずメッセージを引用されたら全員に通知が飛ぶようになっているはずです。

2021-03-02 00:32 UTC, wtks requested changes

2021-03-02 00:32 UTC, wtks commented on service/notification/handlers.go
> +	messageViewerMulticast(ns, ev.Fields["message_id"].(uuid.UUID), &sse.EventData{
messageViewerMulticastは、その瞬間に指定したIDのメッセージのチャンネルを開いているユーザーだけにWSイベントを送る関数で、この`ev.Fields["message_id"].(uuid.UUID)`は引用されたメッセージではなくて引用したメッセージのIDなので、イベントを送る対象として間違っています。

このイベントが送られるべきなのは、引用されたメッセージを投稿したユーザーのみですね

2021-03-02 00:32 UTC, wtks commented on service/notification/handlers.go
> +			"message":    ev.Fields["message"].(*model.Message),
WSイベントの中身ではIDしか通知しない方針なので、ペイロードには`message`本体(`model.Message`構造体)は含めないでください
```suggestion
```

2021-03-02 00:32 UTC, wtks commented on service/notification/handlers.go
> +			"message":    ev.Fields["message"].(*model.Message),
通知するのは引用を行ったメッセージのメッセージID`message_id`, 引用を行ったメッセージのチャンネルID`channel_id`, 引用を行ったメッセージを投稿したユーザーのID`user_id`でお願いします。

この３つで、メッセージが引用されたユーザーは、自分のメッセージが誰にどこで引用されたかが分かります

2021-03-02 00:33 UTC, wtks commented on service/notification/handlers.go
> +		}
引用メッセージとメンションメッセージを同じ通知処理にしていいかどうかは今検討中

2021-03-02 03:57 UTC, wtks commented on service/notification/handlers.go
> +				return
ここ一応continueにしといてください

2021-03-02 04:24 UTC, hijiki51 commented on service/notification/handlers.go
> +			"message":    ev.Fields["message"].(*model.Message),
userMultiCastの引数はたぶんイベントを送るユーザーだと思うのですが、これってどうやったら取れますか？引用されるメッセージは一つとは限らないのでうまく思い浮かばないのですが…

2021-03-02 04:29 UTC, hijiki51 commented on service/notification/handlers.go
> +			"message":    ev.Fields["message"].(*model.Message),
あとここを書き換えるなら
`massmage_impl.go:59`と`topic.go:117`との整合性が取れなくなりそうですが大丈夫なんでしょうか？

2021-03-02 04:32 UTC, wtks commented on service/notification/handlers.go
> +			"message":    ev.Fields["message"].(*model.Message),
引用を行ったメッセージのチャンネルID`channel_id`, 引用を行ったメッセージを投稿したユーザーのID`user_id`は`ev.Fields["message"].(*model.Message)`から取り出してください

2021-03-02 04:34 UTC, wtks commented on service/notification/handlers.go
> +			"message":    ev.Fields["message"].(*model.Message),
userMultiCastの引数に関しては、https://github.com/traPtitech/traQ/blob/461583819e940fa315f27e2e8eb1fd480bd76ce9/service/notification/handlers.go#L188 と同様にforで回して取り出せばOKです

2021-03-02 07:27 UTC, hijiki51 commented
こんな感じでいいでしょうか(Lintがおわらない…)

2021-03-02 14:21 UTC, wtks commented on service/notification/handlers.go
> +				"user_id":    ev.Fields["user_id"].(*model.Message).UserID,
Fields["message"]ですね

2021-03-02 14:24 UTC, wtks commented
あとswaggerのWSのドキュメントにMESSAGE_CITEDイベントについてを追記しといてください
https://apis.trap.jp/#/notification/ws

https://github.com/traPtitech/traQ/blob/master/docs/v3-api.yaml

2021-03-02 15:20 UTC, hijiki51 commented on service/notification/handlers.go
> +				"user_id":    ev.Fields["user_id"].(*model.Message).UserID,
修正しました

2021-03-03 00:31 UTC, wtks approved these changes
LGTM

2021-03-03 00:32 UTC, merged