ピン留め上限の設定
traPtitech/traQ pull request #1256
Opened 2021-07-17 17:45 UTC by logica0419

Fixes #1215

2021-07-17 17:53 UTC, logica0419 commented
*_impl.go が *.go のインターフェースの実装ファイルだと今日初めて知りました (遅い)
とりあえず2時間ほどいろんなコードを飛びながら実装して、手元環境で上限設定できたのが確認できたのでPRを出します
チャンネルのピン留めの数、ピン留めされたメッセージ一覧のスライスの長さで取っているので、もっとスマートに抽出できそうなら指摘していただきたいです…

2021-07-17 17:59 UTC, logica0419 commented on service/message/manager.go
> +	// チャンネルに既に100個以上のメッセージがピン留めされていた場合、"pin limit reached"エラーを返します。
エラーの書き方これでいいですか…？

2021-07-17 18:01 UTC, logica0419 commented on service/message/manager_impl.go
> +	pinLimit := 100 // ピン留めの上限数
後々の人が上限変えやすいようにpinLimitを宣言するようにしましたが、無駄かな～とも思っています
宣言する位置はもしかしたら変えたほうがいいかも

2021-07-17 18:08 UTC, logica0419 reviewed
これは投稿ミス

2021-07-17 18:15 UTC, logica0419 reviewed
自分で気になってるポイントはこの2つです。よろしくお願いします。

2021-07-17 18:15 UTC, logica0419 commented on service/message/manager.go
> +	// チャンネルに既に100個以上のメッセージがピン留めされていた場合、"pin limit reached"エラーを返します。
エラーの書き方これでいいですかね？

2021-07-17 18:15 UTC, logica0419 commented on service/message/manager_impl.go
> +	pinLimit := 100 // ピン留めの上限数
後々上限数を変更するとき一発でわかるように、変数でピン留めの上限を宣言する形にしました。constの方が良かった説はある。
```suggestion
	const pinLimit = 100 // ピン留めの上限数
```
いらないかもな～とは思っているので、もしいらなそうなら指摘お願いします。
あとはわかりやすいところに宣言だけ動かしてもいいかも？

2021-07-17 23:58 UTC, motoki317 requested changes
一度動くところまで確認しているのはとても良いです :+1:
もう少しやることはあるので、コメントしました

2021-07-17 23:58 UTC, motoki317 commented on service/message/manager_impl.go
> +	pinLimit := 100 // ピン留めの上限数
いや、それの方が分かりやすいので良い書き方です。
これはconstにして良いですね

2021-07-17 23:58 UTC, motoki317 commented on service/message/manager_impl.go
> +	pins, err := m.R.(*repository.GormRepository).GetPinnedMessageByChannelID(msg.GetChannelID())
この`(*repository.GormRepository)`のキャストは要らないはずです。

データを保存するrepositoryはわざわざ`repository.Repository`というinterfaceにしてservice層に渡すことで、"詳細を隠して"います。依存関係の逆転とか依存関係の注入(dependency injection)といったものです。
こうすることでテストなどが可能になります。

2021-07-17 23:58 UTC, motoki317 commented on service/message/manager.go
> +	// チャンネルに既に上限数以上のメッセージがピン留めされていた場合、"pin limit reached"エラーを返します。
上のエラーの返し方を見てもらうと分かると思うのですが、例えば
> 既にピンされている場合は、ErrAlreadyExistsを返します。

とあって、既にピンされている場合は`service/message/manager.go#L14`に事前に定義されているErrAlreadyExistsというエラーを返しています。（呼び出すたびにエラーを生成するのではなく）
なぜこうしているかは、ErrAlreadyExistsがどこで使われているかを見ると分かるので、少し見てみて、このパターンに従うように書いてみてください。

2021-07-18 03:57 UTC, logica0419 commented on service/message/manager_impl.go
> +	pins, err := m.R.(*repository.GormRepository).GetPinnedMessageByChannelID(msg.GetChannelID())
なるほど！全ての`repository.〜Repository`型に`repository.Repository`インターフェースを実装することによって、全ての`〜Repository`型に対して`Repository`インターフェースで宣言されたメソッドを使用できるという理解で合ってますかね？
今回のこれは型変換のつもりで付けてなくて、メソッドと関数ごっちゃになってて、パッケージ指定したつもりでした…メソッド実装した型に対して直付けでメソッド実行できるの忘れてた
あれ？でも`GormRepository`って`Repository`を実装した構造体ですよね？`GormReposiry`にあって`Repository`にないフィールドを使ったメソッドの場合`Repository`インターフェースを実装した構造体というだけでは使えないことが起こるのかな？って今思って… その危険性があるとすると今回の`GormRepository`に実装されたメソッドを`Repository`インターフェース型に対して使うって許されるんですか？

2021-07-18 04:01 UTC, logica0419 commented
> 一度動くところまで確認しているのはとても良いです :+1:

実際はpinLimit=10の状態でビルドして確認してるので100になった時予想してない挙動をするかもしれない…

2021-07-18 04:01 UTC, logica0419 commented on service/message/manager.go
> +	// チャンネルに既に上限数以上のメッセージがピン留めされていた場合、"pin limit reached"エラーを返します。
頑張って伝達先を探します

2021-07-18 04:27 UTC, motoki317 commented on service/message/manager_impl.go
> +	pins, err := m.R.(*repository.GormRepository).GetPinnedMessageByChannelID(msg.GetChannelID())
ちょっとよく理解できなかったんですが、多分interfaceの理解がまだ微妙なので(Goのinterfaceの)基本的なことを確認してみると良いです。
interface <-> interfaceを実装している型 の関係は一対多の関係になります。
https://tour.golang.org/methods/1

2021-07-18 04:37 UTC, logica0419 commented on service/message/manager_impl.go
> +	pins, err := m.R.(*repository.GormRepository).GetPinnedMessageByChannelID(msg.GetChannelID())
頑張って勉強します…

2021-07-20 18:58 UTC, logica0419 commented on service/message/manager.go
> +	// チャンネルに既に上限数以上のメッセージがピン留めされていた場合、"pin limit reached"エラーを返します。
恐らくですが見当がつきました
BadReqest(400)として返さなければ行けないものをErrAlreadyExistsとErrChannekArchived、ErrNotFound(Pinでは返り値で定義されているけど呼び出し元のCreatePinではswitch文のcaseに入ってなくてなんか違和感あったけど)として定義していて、それ以外をInternalErr(500)として返すようにしているということですよね… 今はInternalErrで他のと区別せず返しているからInternalErrとして扱われて、「ピン留めに失敗しました」しか出てこないようになってるんですよね。
今回、UIの方で「上限に達しました」を出したい場合はErrPinLimitReached(名づけるとしたら)をBadRequestとして返すのがいいですよね… そしたら新たな定義した方がいいですか？

2021-07-20 22:44 UTC, motoki317 commented on service/message/manager.go
> +	// チャンネルに既に上限数以上のメッセージがピン留めされていた場合、"pin limit reached"エラーを返します。
そうですね、そうして下さい。

2021-07-21 19:57 UTC, logica0419 commented
一応BadRequestで返すようにしました。
フロントでどんな処理してるかによってエラーのの中身決めようと思ったんですけど、フロント全くわからんになってるので仮置きです。ヤバいことをしているかも。そもそも可変でええんか。
あとPinLimitをエラー文にぶちこみたいがためだけにグローバル変数にしました。我ながらめちゃくちゃやってると思います。上に書いた通り可変エラー良くなさそうなら、これは関数スコープの変数に戻します。
色々ツッコミどころはあると思いますがよろしくお願いします。

2021-07-22 01:14 UTC, motoki317 approved these changes
良いと思います。

APIで返すメッセージは変なものでなければとりあえず良いかなと思います（クライアントは今は分けて

2021-07-22 01:17 UTC, merged

2021-07-22 04:25 UTC, logica0419 commented
swaggerの定義の変更、Webhook通してすごい色々繋がってるって聞いたけどわかってないですし、テストの方も仕組み全然理解してないのでできればやってみたい思いはありますが…

2021-07-22 04:37 UTC, motoki317 commented
swaggerとWebhookは全くの別の概念ですよ(一応)

`docs/v3-api.yaml`に定義があり、ここにAPIのパスやリクエスト/レスポンスの形などをドキュメント化しています
今回はリクエストやレスポンスの形が変わったわけではないので変更は不要といえば不要ですが、 https://apis.trap.jp/#/message/createPin の説明に「上限を超えてピン留めしようとするとBad Requestを返すよ」ということは書いておいてもいいかなという話です