環境変数を設定するのを忘れていました
traPtitech/traQ pull request #126
Opened 2018-02-24 01:55 UTC by masutech16

申し訳ないです。取得するようにしました

2018-02-24 07:13 UTC, kaz requested changes
dirNameはdevFileManagerのメンバであるほうが良い
setDirは止めて、コンストラクタ的な関数を作って、そこで環境変数を読んでdirNameを設定したdevFileManagerを返すべき

2018-02-25 06:41 UTC, masutech16 commented
router側のテストでもファイルを消す必要があったのでdevFileManagerを公開して、GetDir()で保存するディレクトリをとれるようにしました。
また、すべてのレシーバで最初にdirNameを初期化するようにしました
ちょっと仕様とは変わっているかもしれませんがどうでしょう

2018-02-25 15:57 UTC, kaz commented
> また、すべてのレシーバで最初にdirNameを初期化するようにしました

これをやる理由がわかりません

コンストラクタ`func NewDevFileManager() *DevFileManager`で現在の`setDir()`に相当する処理行うほうが効率的で妥当だと思うのですが、どうでしょうか。

2018-02-26 03:44 UTC, masutech16 commented
勉強になります。訂正しました。

2018-02-26 14:59 UTC, kaz approved these changes

2018-02-26 15:04 UTC, merged