`GET /stamps`にtypeクエリを追加
traPtitech/traQ pull request #1426
Opened 2022-04-20 05:48 UTC by logica0419

`type`は`unicode`/`original`が指定できる
typeを省略すれば今まで通り`include-unicode`でも指定できるようにしてあります

2022-04-20 05:50 UTC, sapphi-red commented on utils/twemoji/installer.go
> +	emojiMetaURL = "https://raw.githubusercontent.com/joypixels/emoji-toolkit/master/emoji.json"
URL変える必要があるのはここだけじゃないのと、このPRに関係ないので別のPRで出すほうがいいですね

2022-04-20 05:51 UTC, logica0419 commented
Open API定義ってswagger.yamlとv3-api.yamlどっちも変える必要ありますか？

2022-04-20 05:53 UTC, sapphi-red commented
swagger.yamlはv2用でほぼ廃止されてるので項目自体存在しないはずです

2022-04-20 05:54 UTC, logica0419 commented
Docsにまだ残っているんですけどこれがまだ使われてるところってありますかね？

2022-04-20 05:57 UTC, sapphi-red commented
ごめんなさい
項目っていうのが曖昧でした
ファイルは残っててAPIはほとんど廃止されているっていう意図でした
https://apis.trap.jp/?urls.primaryName=traQ%20v2%20API

2022-04-20 05:58 UTC, sapphi-red commented
残ってるAPIは細かいところで使われてるとこがないこともなかった感じだった気がします (libraでloki絞込かければ見つかるかな)

2022-04-20 06:58 UTC, sapphi-red commented on docs/v3-api.yaml
> +          description: (Duplicated) Unicode絵文字を含ませるかどうか
```suggestion
          deprecated: true
          description: |-
            Unicode絵文字を含ませるかどうか
            Deprecated: typeクエリを指定しない場合はすべて取得できるため、それを利用してください
```
https://swagger.io/specification/#operation-object
`deprecated`が存在するので使ったほうが良いですね
あとは、ほかに合わせるとよさそうです
https://github.com/traPtitech/traQ/blob/e5d819baea72a65cb8b3ea59bb18d7dd034ccd0e/docs/v3-api.yaml#L4651-L4657

2022-04-20 08:07 UTC, sapphi-red commented on docs/v3-api.yaml
> +          duplicated: true
duplicatedじゃなくて**deprecated**ですね
(重複じゃなくて**廃止予定**)

2022-04-20 11:47 UTC, motoki317 commented on repository/gorm/stamp.go
>  		}
もしかして: 逆

2022-04-20 11:47 UTC, motoki317 commented on repository/stamp.go
> +	GetAllStamps(stampType int) (stamps []*model.Stamp, err error)
ただのintは分かりにくそうだからどこかにconstを定義したいですね

2022-04-20 12:34 UTC, logica0419 commented on repository/gorm/stamp.go
>  		}
かなり逆くさい

2022-04-20 12:35 UTC, logica0419 commented on repository/stamp.go
> +	GetAllStamps(stampType int) (stamps []*model.Stamp, err error)
どこがいいですかね

2022-04-20 12:55 UTC, motoki317 commented on repository/stamp.go
> +	GetAllStamps(stampType int) (stamps []*model.Stamp, err error)
別にこだわりは無いのでどこでも良いと思います
このRepositoryのinterfaceの定義の上に引数の型の定義があるのでそこに同じように定義するとか

2022-04-20 19:44 UTC, logica0419 commented
こんなもんでどうでしょ

2022-04-21 00:03 UTC, sapphi-red reviewed
それと、テストを書いたほうがよさそうです

2022-04-21 00:03 UTC, sapphi-red commented on router/v3/stamps.go
> +	}
想定してないものが指定されたときは400返すのが親切そうです

2022-04-21 02:17 UTC, motoki317 commented on router/v3/stamps.go
> +	}
↑をしようとすると、リクエストをvalidateする→不正な値なら400を返す→対応するスタンプを返す、の流れが認知的にも楽だと思うので、他のhandlerの実装を見ながらやると良さそう

2022-04-22 17:15 UTC, sapphi-red requested changes

2022-04-22 17:15 UTC, sapphi-red commented on router/v1/public.go
> +	stamps, err := repo.GetAllStamps(repository.StampTypeOriginal)
```suggestion
	stamps, err := repo.GetAllStamps(repository.StampTypeAll)
```
`excludeUnicode=false`に対応するのは`repository.StampTypeAll`っぽそうです

2022-04-22 17:15 UTC, sapphi-red commented on router/v1/public.go
> +	stamps, err := repo.GetAllStamps(repository.StampTypeOriginal)
```suggestion
	stamps, err := repo.GetAllStamps(repository.StampTypeAll)
```

2022-04-22 17:25 UTC, sapphi-red approved these changes
:kansya:

2022-04-23 03:15 UTC, motoki317 approved these changes
よく書けていそう :+1:

GetStampsの処理が複雑になってるので他のhandlerのようにbindAndValidateで分割するか、そこのロジックが合っているかをテストでしっかり保証できると良さそう

routerのテストでrepositoryがモックになっていないのはすまんって感じだ

2022-04-23 03:27 UTC, motoki317 commented
これは別PRで良いので、ETagチャレンジもしたいですね

jsonのエンコード周りがトリッキーっぽそう
このオプションもよく見つけたなって思う
https://github.com/traPtitech/traQ/blob/2087cb6f2afe356a06c73254a876242458bba914/router/extension/precond.go#L198

2022-04-23 14:00 UTC, sapphi-red commented
Last-Modifiedで304返ってくるからETagはなくてもよさそうな感じする

2022-04-23 15:11 UTC, motoki317 commented
ETagの話はLast-Modifiedの今の実装だと再起動に弱いのでという話です...

2022-04-23 15:47 UTC, sapphi-red commented
そういえばそんな話あったね…
まぁでもETagにせずともupdatedAtの一番新しいやつ使うようにするほうがよいと思う

2022-04-26 06:15 UTC, logica0419 commented
一旦マージして、次はVerifierを書きます

2022-04-26 06:15 UTC, merged