チャンネルトピックの上限を500文字に
traPtitech/traQ pull request #1708
Opened 2023-03-06 03:19 UTC by ikura-hamu

resolve: #1682 

500文字にした。ただ、現状フロントエンドで200文字以上のときは決定ボタンが押せないようになっているので、フロントエンドの改修が必要。

2023-03-06 06:08 UTC, logica0419 commented
変更点は良いですね！完璧です。
ただ、今のままだと想定した挙動が保障できないので、テストケースの追加をお願いできますか？
501文字で400番台のどれか(これも確かめて欲しい)のステータスコードが返ってくることを検証したいです

2023-03-12 09:08 UTC, ikura-hamu commented
テストケースを追加しました。確認お願いします。

2023-03-12 15:06 UTC, logica0419 requested changes
素晴らしい出来です！
1箇所修正あるので確認お願いします

2023-03-12 15:06 UTC, logica0419 commented on router/v3/channels_test.go
> +		e.PUT(path, archived.ID.String()).
ここ、アーカイブされてるチャンネルだとテストの意味がなくなっちゃいますので、修正お願いします

2023-03-13 05:55 UTC, ikura-hamu commented on router/v3/channels_test.go
> +		e.PUT(path, archived.ID.String()).
コピペしてそのままでした。修正しました。

2023-03-13 17:19 UTC, logica0419 commented
良い感じです！
言うのが遅くなって申し訳ないのですが、500文字では正常系レスポンスが返ってくることも確かめたいので、そのテストケースも追加できますか？

2023-03-15 06:27 UTC, motoki317 commented on router/v3/channels_test.go
> +			WithJSON(&PutChannelTopicRequest{Topic: "12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345
ちなみに、どちらでも良いのですが、`strings.Repeat` という関数があってそちらの方が読みやすいかもしれないです
```suggestion
			WithJSON(&PutChannelTopicRequest{Topic: strings.Repeat("a", 501)}).
```

2023-03-15 06:29 UTC, ikura-hamu commented on router/v3/channels_test.go
> +			WithJSON(&PutChannelTopicRequest{Topic: "12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345
初めて知りました。ありがとうございます！直します

2023-03-15 07:27 UTC, motoki317 approved these changes
変更のビューがなんか変なの入っちゃってますが、多分大丈夫でしょう
（rebaseしようとしたらforce pushを忘れずに）

2023-03-15 13:19 UTC, logica0419 approved these changes

2023-03-15 13:22 UTC, logica0419 commented
LGTMです！
はじめてなのに色々無茶言っちゃいましたが、全部難なくこなしてくれて素晴らしかったです。
お疲れさまでした

2023-03-15 13:35 UTC, logica0419 commented
それでは自分でマージお願いします

2023-03-17 02:41 UTC, merged