IDの検証
traPtitech/traQ pull request #175
Opened 2018-03-07 08:30 UTC by masutech16

各種ID(userID, messageID, channelID, tagID, pinID, fileID)の検証を行う関数群の実装をしました。
メッセージのモデルだけコメントや内部の変数名・関数名にあたりのリファクタリングをしました。

2018-03-07 09:35 UTC, tohutohu requested changes
リファクタリング等ありがとうございます
かなり読みやすくなって:+1:

2018-03-07 09:35 UTC, tohutohu commented on router/messages.go
> +	uID := c.Get("user").(*model.User).ID
cIDとchannelID, uIDとuserIDが混在しているので直して欲しい
可読性的にはそんなに長くないしchannelID userIDでいいと思うのですがどうでしょう

2018-03-08 04:36 UTC, tohutohu commented
テスト落ちてる

2018-03-08 04:40 UTC, masutech16 commented
stampとコンフリクトしてたところを直した(関数名を変更した影響でundefinedになってた

2018-03-08 04:43 UTC, tohutohu commented
リベースしたの？

2018-03-08 04:45 UTC, masutech16 commented
現行のmasterとしました

2018-03-08 05:12 UTC, tohutohu approved these changes

2018-03-08 05:12 UTC, merged