スタンプ機能
traPtitech/traQ pull request #177
Opened 2018-03-07 11:31 UTC by wtks

```golang
	api.GET("/stamps", router.GetStamps)
	api.POST("/stamps", router.PostStamp)
	api.GET("/stamps/:stampID", router.GetStamp)
	api.PATCH("/stamps/:stampID", router.PatchStamp)
	api.DELETE("/stamps/:stampID", router.DeleteStamp)
	api.GET("/messages/:messageID/stamps", router.GetMessageStamps)
	api.POST("/messages/:messageID/stamps/:stampID", router.PostMessageStamp)
	api.DELETE("/messages/:messageID/stamps/:stampID", router.DeleteMessageStamp)
```
実装したapiは以上、詳細はswagger.yamlで

2018-03-07 23:16 UTC, tohutohu requested changes
大体OKです

スタンプを作った後にスタンプのファイルが削除された場合はどうしますか？
普通に放置でいいですかね

2018-03-07 23:16 UTC, tohutohu commented on router/stamp.go
> +	//TODO 見れないメッセージ(プライベートチャンネル)に対して404にする
このファイルのTODO消せるので消してほしい

2018-03-08 01:12 UTC, wtks commented
TODOを全てした。

2018-03-08 01:59 UTC, tohutohu approved these changes

2018-03-08 01:59 UTC, merged