Official es
traPtitech/traQ pull request #1914
Opened 2023-08-04 03:35 UTC by ikura-hamu

resolve: #1804 

https://github.com/elastic/go-elasticsearch を使った。途中。

2023-08-04 03:48 UTC, ikura-hamu commented
ボリューム削除してから起動すると、管理者の`traq`アカウントが作成されなくなってしまったのですが、なんでかわかりませんでした。
`cmd/serve.go`を見ると、DBスキーマが初期化されたときに管理者アカウントを作るようですが、なぜこれが反応しなくなってしまったのでしょうか。

2023-08-04 08:21 UTC, logica0419 commented
スタートアップ時、Dockerコンテナから今までと違うログは流れていませんか？
masterブランチにcheckoutして起動したら同じ結果になるかどうか確認し、違う結果であればログの相違を比較してまとめてほしいです。

2023-08-05 04:08 UTC, ikura-hamu commented
elastic search の初期化でバグってただけでした。お騒がせしました

2023-08-07 07:04 UTC, ikura-hamu commented
修正終わったので、レビューお願いします。

2023-08-09 03:19 UTC, logica0419 commented
go.modだけ見ましたが、`go mod tidy`はしましたか？
しているということであれば、以前使っていたes clientが使われているコードがまだあるということなので、それらを全て置き換えるか、もしくは置き換えられない理由をここで言ってもらえるとありがたいです

2023-08-09 03:28 UTC, ikura-hamu commented
すみません、忘れてました。

2023-10-12 17:21 UTC, logica0419 requested changes
とにかくありがとう！こんな重い実装やり切ってくれたのはすごくありがたい…
にもかかわらずレビュー遅れてしまって申し訳ないです。
とりあえずコード全域読んで修正点洗い出したので、やってくれると嬉しいな！

2023-10-12 17:21 UTC, logica0419 commented on service/search/engine.go
> -func (q Query) GetSortKey() Sort {
この変更で以下の型が不要になってると思うので、消しといてほしいです
https://github.com/traPtitech/traQ/pull/1914/files#diff-aa0c36769dd3eff22111aa02f0fe5a1967c913d99366571d73509e7d2ffc1cdbR63

2023-10-12 17:21 UTC, logica0419 commented on service/search/es.go
>  type m map[string]interface{}
ちょっと関係ないかもしれないけど、ここもアップデートということで
```suggestion
type m map[string]any
```

2023-10-12 17:21 UTC, logica0419 commented on service/search/es.go
> +	defer infoRes.Body.Close()
Closeはエラーハンドリングが終わった後の方が良いです
(エラー起きてたらnilなこととかあるから)

どうせdeferでにるぽ出てもあまり挙動には関係ないですが、BodyフィールドがあってCloseできることがわかってからdeferの方が礼儀がいい感じがする

2023-10-12 17:21 UTC, logica0419 commented on service/search/es.go
> +	var r map[string]interface{}
こここうすれば後ろの型キャスト排除してJSONのデコードで全部解決できる説ある
```suggestion
	var r struct {
		Version struct {
			Number string `json:"number"`
		} `json:"version"`
	}
```

2023-10-12 17:21 UTC, logica0419 commented on service/search/es.go
>  	}
今回の変更範囲じゃないんだけど、ここログ出す順番逆の方が良い気がしている
(サポートしてないバージョン先にログに出してもなぁと)

2023-10-12 17:21 UTC, logica0419 commented on service/search/es.go
> +	}
ここdefer書く場所上に書いた通りで

2023-10-12 17:21 UTC, logica0419 commented on service/search/es.go
> +	err = json.Unmarshal(infoResBody, &r)
New系関数だからパフォーマンスはあまり気にしなくていいんだけど、io.Readerは一回読み出すよりもそのまま処理した方が速いしメモリも食わないので好ましいです
このライブラリだとこの方がシンプルに書けそうだし
参考: https://pkg.go.dev/github.com/json-iterator/go@v1.1.12#Decoder
```suggestion
	err = json.NewDecoder(infoRes.Body).Decode(&r)
```

2023-10-12 17:21 UTC, logica0419 commented on service/search/es.go
> +			return nil, fmt.Errorf("failed to create Elasticsearch index: StatusCode: %v, ResponseBody: %v", createIndexRes.StatusCode, createIndexRes.Body)
defer書く位置は(略)

2023-10-12 17:21 UTC, logica0419 commented on service/search/es.go
> +	}
defer(略)

2023-10-12 17:21 UTC, logica0419 commented on service/search/es.go
>  	}
jsonのデコード、上記の通りReaderのままやってほしい

2023-10-12 17:21 UTC, logica0419 commented on service/search/es.go
>  }
ここで判定があるの、恐らくここで定義しているClient構造体と、ライブラリのClient構造体のライフサイクルに差異ががあったことの名残なんですよね
traQ側のClient構造体があるのにライブラリのClient構造体を叩けないタイミングが存在するので、そこで叩くとマズいということですね

今回使うofficial es libraryのClient構造体は特にライフサイクルが無いので、ここは単純にtrueを返すだけでよさそうな気がしています(runningフィールドは用意しなくてよい)
traQのClient構造体がある時必ず叩ける、であれば問題ないはずなので

2023-10-12 17:21 UTC, logica0419 commented on service/search/es_result.go
> +		MaxScore interface{}   `json:"max_score"`
any型でお願い！

2023-10-12 17:21 UTC, logica0419 commented on service/search/es_result.go
> +		totalHits: int64(totalHits),
ここもともとint64だから型キャストいらなそう

2023-10-12 17:21 UTC, logica0419 commented on service/search/es_result.go
> +func (e *esEngine) parseResultBody(resBody esSearchResponse) (Result, error) {
【そんなに気にしなくても良い】
ここ、型名と実際の変数名・関数名がちょっとずれちゃってるかな…と思うので、ちょっとネーミング考えてみてくれると嬉しいな

2023-10-12 17:21 UTC, logica0419 commented on service/search/es_sync.go
> +
ここスペース空いてるのちょっとキモいので消してもらいたいなぁ(個人の感想)

2023-10-12 17:21 UTC, logica0419 commented on service/search/es.go
> +		e.client.Search.WithContext(context.Background()),
すっごい細かいんだけど、Context渡すのってOptionalで、context.Background()は何も効果が無いからここで書いても書かなくても一緒な気がする
今回はWithContext削除しちゃってくれ

2023-10-12 17:21 UTC, logica0419 commented on service/search/es_sync.go
>  	}
JSONのデコードは上の通りで

2023-10-12 17:21 UTC, logica0419 commented on service/search/es_sync.go
> +		e.client.Search.WithContext(context.Background()),
Contextに関しては上の通りで

2023-10-13 20:27 UTC, logica0419 reviewed
ちょっと1か所だけ意見欲しい

2023-10-13 20:27 UTC, logica0419 commented on service/search/es.go
> +	URL []string
今更ではあるがここをリストにする意味はあるのかちょっと疑問に思ってます
単一elasticsearchクライアントを想定しているから、traQの提供するConfigとしてはstringのままで良いのでは？という

2023-10-14 04:45 UTC, ikura-hamu commented on service/search/es.go
> +	URL []string
たしかに。1個だけにしておきます

2023-10-14 17:17 UTC, logica0419 approved these changes
LGTM
お疲れさんでした👏

2023-10-15 01:07 UTC, merged