レスポンスにサムネイル情報追加
traPtitech/traQ pull request #1929
Opened 2023-08-13 22:04 UTC by azbcww

サムネイル情報をGET /api/v3/stamps のレスポンスに載るよう変更しました．
"hasThumbnailを含める"っていうのをサムネイル情報が欲しいって解釈したんですけど返す情報違いますかね．．．？

あと実装面も自信ないので何かあれば教えてほしいです．．．
お願いします．

2023-08-16 04:02 UTC, ikura-hamu commented
ありがとうございます。

僕は`hasThumbnail`というbool値をレスポンスに含めるのだと思ってましたが、 @motoki317 さんはissueを立てた時、どういうのを意図していましたか？

2023-08-16 07:16 UTC, motoki317 commented
このissueの目的は、UIの省エネモードでアニメーションのスタンプを表示しないために、サムネイルを代わりに表示したいことです
そのために現状はファイルの `/files/:fid/meta` をいちいち叩かないと `/files/:fid/thumbnail` が存在するかわからないので、サムネイルが存在するかを一気に取りたいという意図です
https://q.trap.jp/messages/93892217-e704-4104-ad00-166851650d90

なので、bool値で十分だと思います

2023-08-16 07:21 UTC, motoki317 commented on router/v3/stamps.go
> +		ts, err := h.Repo.GetFileMeta(stamp.FileID)
このようにループで取得すると、(DBまでのRTT: 0.1~10ms目安) x (ループ回数: 今回は6800を超える) が直接レスポンスに加算される形で遅くなり、俗に「N+1問題」などと言う、場合によってはレスポンスの速度にひどく悪影響を与えるパターンです。
スタンプの数: https://q.trap.jp/api/v3/stamps

今回はループの回数がかなり多いので、いくらキャッシュされるとはいえ、ループで取得するのは避けたいですね

2023-08-16 07:24 UTC, motoki317 commented on router/v3/stamps.go
> +		ts, err := h.Repo.GetFileMeta(stamp.FileID)
より分かりやすく言うと、これをすると、`/stamps` はUI起動時に叩かれるはずなので、traQを開く速度が5秒遅くなります

2023-08-18 03:55 UTC, azbcww commented on router/v3/stamps.go
> +		ts, err := h.Repo.GetFileMeta(stamp.FileID)
コードレビューありがとうございます．
この方法ではDBまでデータを取りに行くことになるんですね．．．
実装方法もう少し探ってみます！

2023-08-21 02:57 UTC, azbcww commented
スタンプに対応したサムネイルを取得できる既存のメソッドを探したのですが見つけることができなかったので助言をいただきたいです．

やろうとしたこと
スタンプのファイルIDからファイルメタを取得してサムネイルの有無を調べようとした．

現状
GetAllStamps()でmodel.Stamp構造体の配列を取得している．

問題
上記配列にあるすべてのファイルIDからファイルメタを，DBへの問い合わせ1往復のみで行いたいが方法が見つからない．

手詰まり感あるので想定している実装方法などあればヒント欲しいです．．．

2023-08-22 14:38 UTC, ikura-hamu commented
遅くなってごめんなさい。

忙しくてちゃんとコードを読めてないのですが、データベースでサムネイルの存在を確かめるメソッドを書く必要があると思います。

docs/dbSchema にあるデータベーススキーマと、repositroryで定義されているinterfaceとそのgormの実装を参考にして、ループ回さず必要な情報を取得できるメソッドをお願いします。

2023-08-23 06:41 UTC, azbcww commented
返信ありがとうございます！

教えていただいたことを参考にしながらやってみます！

2023-10-04 07:45 UTC, azbcww commented
前の変更からだいぶ時間たってしまいましたがdbから一度のクエリでスタンプのサムネイル情報を取得できるようにしました．
しかし，CIのエラーが出ており解決したいのですが見方が分からず困っています．
どこを見ればいいかおしえていただけないでしょうか？

2023-10-04 09:13 UTC, motoki317 commented
LintとTestの2つFailしてますね。一つずつ見ましょうか

Lintの方は、`file is not gofmt-ed` というメッセージが出ていますが、文字通り、ファイルが「gofmt」でフォーマットされてないよということです。Goには言語標準のgofmtというフォーマッタがあるので、それでフォーマットしてねということです。
https://github.com/traPtitech/traQ/actions/runs/6402762003/job/17383151638
![image](https://github.com/traPtitech/traQ/assets/18257693/825cc21c-8742-4802-9ba2-8676eaa838e4)

Testの方は、↓のチェックが失敗しているようですね。APIのレスポンスとしてJSONのArrayが返ってくることを期待したけど、実際には `nil` という文字列が返ってきているようです。
https://github.com/traPtitech/traQ/blob/469b8dbbb271cb18fa29bc514f297a008d3e1881/router/v3/stamps_test.go#L115
Goでは実はsliceのゼロ値(nil)と、`make([]T, 0)` などで作った長さ0のsliceは違って、JSONにエンコードするときも前者は `nil` ]に、後者は `[]` になります。これを考慮してみてください
https://github.com/traPtitech/traQ/actions/runs/6402762003/job/17379996280
![image](https://github.com/traPtitech/traQ/assets/18257693/c083cbd9-903f-46e3-a3b3-935f4f012044)

2023-10-04 09:17 UTC, motoki317 commented
Testの方の補足です
https://go.dev/play/p/WTdS_ZpLYfp

2023-10-04 12:23 UTC, azbcww commented
エラー内容を教えていただきありがとうございます！
参考にして修正したらエラー消すことができました

修正完了したので内容についても時間があるときに見てほしいです
処理を書く場所や処理方法の改善があれば教えていただければと思います
よろしくお願いします！

2023-10-05 11:09 UTC, ikura-hamu requested changes
ありがとうございます！実装は大丈夫だと思います。1か所だけリファクタリングお願いします。

また、今回の変更部分のテストコードを書いてほしいです。

repositoryの`StampThumbnailExists()`のテストは repository/gorm/stamp_test.goに書いてください。
routerの`GetStamps()`のテストはrouter/v3/stamps_test.goで修正を加えてください。

他のテストの関数を参考にすると書きやすいと思います。
GetStampsの方は、レスポンスボディが変わっているので、その評価を行う部分に修正が必要です。

何かわからないことがあったら聞いてください。お願いします！

2023-10-05 11:09 UTC, ikura-hamu commented on repository/stamp.go
> +type StampWithThumbnail struct {
Goでは

```go
type StampWithThumbnail struct {
  model.Stamp
  HasThumbnail bool      `json:"hasThumbnail"`
}
```

のようにフィールド名を省略して構造体に構造体を埋め込むことができます。これを使うことで`StampWithThumbnail`が`model.Stamp`を含んでいることが分かりやすくなるし、 repository/gorm/stamp.go をもう少しシンプルに書けそうです。

2023-10-18 07:33 UTC, azbcww commented
実装確認していただきありがとうございました！
指示もどこを修正すればいいのかわかりやすく助かりました！

指摘してくださったことを踏まえ構造体の修正とテストコードの追加を行いました．

ただテストコード自体はこれでいいのかよくわからなかったので確認していただけると助かります．
また，api/v3/stampsのレスポンスを行うメソッドであるGetStampsのレスポンス内容を変更しているのでSwaggerのレスポンス内容も書き換えた方がよいでしょうか？

時間あるときに確認していただければと思います．
よろしくお願いします．

2023-10-21 02:33 UTC, ikura-hamu reviewed
ありがとうございます！

repositoryの方のテストでいくつか修正をお願いします。
routerの方はいいと思います。

そうですね、swaggerの方もレスポンスボディのフィールドの修正をお願いします。

2023-10-21 02:33 UTC, ikura-hamu commented on repository/gorm/stamp_test.go
> +		arr, err = repo.GetAllStamps(repository.StampTypeAll)
ここでGetAllStampsを実行しなくても、`mustMakeStamp`の返り値が*model.Stampなので、それを順番にスライスにappendしていけば`arr`と同じものが得られます。
（なんなら上のGetAllStampsも無くして、`mustMakeStamp`で作ったやつだけにしてもいいかもしれません）

2023-10-21 02:33 UTC, ikura-hamu commented on repository/gorm/stamp_test.go
> +	if assert.NoError(err) {
GetAllStampsは今回のテスト対象ではないので長さを確かめる必要はありません。errがnilではないなら、`t.Fatalf()`でテストを抜けるとよいと思います。

2023-10-21 02:33 UTC, ikura-hamu commented on repository/gorm/stamp_test.go
> +		assert.Len(arrWithThumb, n)
`assert.Len`では、スライスなどの長さが等しいことを確かめますが、その中身が正しいかどうかは判定していません。
今回は`arrWithThumb`に`HasThumbnail`があって`true`になっているかどうかと、stampの情報が変わってしまっていないかを確認してほしいです。
`assert.Equal()`を使うといいと思います。

2023-10-21 02:33 UTC, ikura-hamu commented on repository/gorm/stamp_test.go
> +
サムネイル画像が無い場合にちゃんとfalseが返って来るかの確認もやりたいです。`t.Run()`を使って、他のところと同じ感じに2つのテストケース(サムネイルがある、ない)を書いてください。

`mustMakeStamp`は必ずサムネイルを作るようになっているので、そのままは使えません。少しめんどくさくなってしまいますが次のどちらかをやって欲しいです。
1. repository_test.goの`mustMakeStamp`とその内部で呼ばれている`mustMakeDummyFile`に`hasThumbnail`のような新しい引数を作り、サムネイルを作るかどうかを決めれるようにする。
2. 新しく`mustMakeStampWithoutThumbnail`、`mustMakeFileWithoutThumbnail`を作る。

実装としては1の方がきれいな気がしますが、`mustMakeStamp`とかは使われている箇所が多くて変更が大変なので、どちらにするかはお任せします。

2023-10-21 05:43 UTC, logica0419 commented
レビューフローに割り込んでしまってすみません。

「StampThumbnailExists」の名前がちょっと気持ち悪いなぁと思って色々考えてたんですけど、その途中で「そもそもGetAllStampsWithThumbnailみたいにした方がいいのでは？」という考えが浮かびました。
根本の実装方針から覆してしまいそうで申し訳ない…
StampThumbnailExistsに渡すstampsって多分GetAllStampsで取るのしか無いから、それならその2つはまとめて1つのメソッドとして確立させた方がわかりやすいのでは？という考えですね。

すでにやっているかもしれませんが、こういう時に気にすべきは、次にこのメソッドを使って別機能を実装する人のことです。
StampRepositoryはinterface、すなわちリポジトリ(データ永続化)機能への入り口ですから、機能を使う人にとって明快で使いやすい入り口を用意するという目線で検討してほしいと思います。

@azbcww @ikura-hamu の2人の意見も聞きたいですが、ちょっと実装方針を再検討してもらえると嬉しいです。
その結果今の形でいきたい、となったらそれはそれで構いません。よろしくお願いします。

2023-10-21 08:31 UTC, azbcww commented
@ikura-hamu 
テストコードの確認ありがとうございます！
いろいろ指摘していただいたことで何をテストすればいいのかわかりました，ありがとうございます<(_ _)>

@logica0419 
実装方針の指摘ありがとうございます！
たしかに１つのメソッドにまとめた方が見栄えがいいですね．．．

@ikura-hamu @logica0419 
僕としては実装時にtraQの思想を十分理解できていたわけではないので実装方針をこうやって提示していただけるのはありがたいです！
また，今回ここまで実装し皆さんのレビューを受けたことで，実装の流れや思想も何となく理解することができたので修正する手間は最初程かからないと考えています．
故に今後わかりやすくなるように実装しなおすのもありだと考えています．
そうなるとikura-hamuさんたちにレビューしていただいたところも最初からやり直しになってしまいますが．．．大事なところは変らないと思うので実装時にめちゃくちゃ参考にさせていただくつもりです！

2023-10-22 10:57 UTC, ikura-hamu commented
@logica0419 ( @azbcww )
むしろコメントもらってありがたいです。確かにって感じなので、大変かもしれませんが再実装の方が良さそうです。よろしくお願いします。

2023-11-27 11:24 UTC, azbcww commented
また時間が空いてしまったのですが修正をしたのでテストを書く前にこの実装方法で良いか一度確認してほしいです．
以下変更点と懸念点です．
お時間あるときに確認していただけると幸いです．
よろしくお願いします．

変更点:
GetAllStampsをGetAllStampsWithThumbnailに書き換えた．
それに伴い，stampRepository構造体要素のperTypeをStamp構造体のキャッシュから，Stamp構造体+HasThumbnailの構造体(以降StampWithThumbnail)のキャッシュに変更．

懸念点:
stampRepository構造体要素のstampsもStampWithThumbnailのキャッシュにすればコードは綺麗になりそうではあったが，GetAllStamps変更のためにそこまで変える必要があるのか不明であったためperTypeのみ変更した．

2023-11-27 21:11 UTC, logica0419 requested changes
ありがとう！
実装は問題無さそうでした！素晴らしいです

細かい書き方に関する指摘を数ヶ所しましたが、基本方針は完璧だと思います！

2023-11-27 21:11 UTC, logica0419 commented on repository/gorm/stamp.go
> +		return stampsWithThumbnail, err
ここの第一返り値はnilを返してほしいです(errあったらnilを返す、というのが綺麗なので)

2023-11-27 21:11 UTC, logica0419 commented on repository/gorm/stamp.go
> +		_, ok := tm[stamp.FileID]
IDの存在判定、これでも悪くないのですが、map化するのちょっと冗長かもなぁという気がします
ここはそこまで効率よくやらなければいけない処理ではないと思うので、どっちかと言うとここはコードのわかりやすさ重視したいかもです

ちょうどGo1.21で標準パッケージ化したこれとか使えそう
https://pkg.go.dev/slices#Contains

2023-11-27 21:11 UTC, logica0419 commented on repository/gorm/stamp.go
> +	ts := make([]uuid.UUID, 0, len(stamps))
ちょっと変数名で指してるものがわかりづらいので、もう少し説明的にしてもらえると助かります

2023-11-27 21:11 UTC, logica0419 commented on repository/stamp.go
> +	// GetAllStampsWithThumbnail 全てのスタンプを取得します
「サムネイル情報を含む」ことをメソッド説明に明記してもらえるとありがたいです

2023-11-27 21:13 UTC, logica0419 commented
stampsキャッシュの書き換えは、今回は必要なさそうなので無くていいと思います
使わない情報持ってても…という感じがするので

2023-11-28 00:14 UTC, motoki317 commented on repository/gorm/stamp.go
> +		_, ok := tm[stamp.FileID]
本番環境ではN=7300程度になるので、キャッシュがよく効く処理とはいえど、流石にO(N^2)は気にしませんか？

2023-11-28 06:38 UTC, logica0419 commented on repository/gorm/stamp.go
> +		_, ok := tm[stamp.FileID]
Goの内部処理だしそんな気にする必要ないかなーと思ってしまった
ちょっと本番データ持ってきて計測してみますか…

2023-11-28 06:42 UTC, logica0419 commented on repository/gorm/stamp.go
> +		_, ok := tm[stamp.FileID]
@azbcww 
本番データ持ってくるのはメンテナーしかできないので、ここは一旦そのままでお願いします
それ以外のところの修正できたらテスト書くのに移ってくれると嬉しいです！

2023-11-28 15:54 UTC, azbcww commented
コードの確認ありがとうございます！

修正を終えてテストを書いているのですが実装方法で質問があります．

やりたいテストは下記のものです．
https://github.com/traPtitech/traQ/pull/1929#discussion_r1367603876
> サムネイル画像が無い場合にちゃんとfalseが返って来るかの確認もやりたいです。`t.Run()`を使って、他のところと同じ感じに2つのテストケース(サムネイルがある、ない)を書いてください。

このテストでサムネイルのないスタンプを作る実装方法を迷っています．
まず，実装方法として次の2つを提案していただきました．
> 1. repository_test.goの`mustMakeStamp`とその内部で呼ばれている`mustMakeDummyFile`に`hasThumbnail`のような新しい引数を作り、サムネイルを作るかどうかを決めれるようにする。
> 2. 新しく`mustMakeStampWithoutThumbnail`、`mustMakeFileWithoutThumbnail`を作る。

1. 2.どちらの実装方法でもmustMakeStamp内のrepo.CreateStampでサムネイルが存在している場合のみスタンプを作成しているため，サムネイルを作らずスタンプを作成する方法を書くのが大変だなと感じています．

そこで，mustMakeStampでサムネイルの存在するスタンプを作成後，repo.DeleteFileMeta()でサムネイルを削除すれば結果的にサムネイルの無いスタンプを得られると考えたのですがこちらの実装方法では良くないところがありますでしょうか？

時間があるときに教えていただけると助かります．
よろしくお願いします．

2023-12-01 09:54 UTC, azbcww commented
テスト追加しました．
サムネイルありスタンプ10個，サムネイルなしスタンプ10個作成しその個数をそれぞれテストしています．
確認よろしくお願いします．

2023-12-03 00:13 UTC, logica0419 reviewed
ありがとう！返信できてなくてごめんなさい…

修正・テスト共に良さそうです！DeleteFileMetaでの実装も良いと思います。
一応1箇所指摘をしておきました。

また、今回APIが返すデータ型に変更があるので、docs/v3-api.yamlをそれに合わせる必要があります(知ってたらすみません)。
OpenAPIという規格に則っているので、それに従って改変をお願いします。わかんないことあったら聞いてください。

2023-12-03 00:13 UTC, logica0419 commented on repository/gorm/stamp_test.go
> +		}
ちょっとifの中身長いかなぁと思ったんで、以下の記事のようにErrorあったら即Failするという形にしてもらった方が嬉しいです！
https://qiita.com/tomtwinkle/items/0c0e79d10bf69ab8fd95

2023-12-03 06:50 UTC, azbcww commented
確認&指摘ありがとございます！
修正しました！
時間あるときで全然大丈夫なので確認よろしくお願いします．

2023-12-04 17:10 UTC, logica0419 requested changes
修正は完璧ですね！ありがとうございます
OpenAPIスキーマの方、修正して欲しいポイントがあるのでお願いします～

2023-12-04 17:10 UTC, logica0419 commented on docs/v3-api.yaml
> +          description: サムネイルの有無
この「Stamp」という構造体は、`GET /stamps/{stampId}`や`POST /stamps`のレスポンスでも使われています (`$ref: '#/components/schemas/Stamp'`でyaml内を検索するとわかるかと思います)
それらはレスポンスの型を変えていないので、今回は「StampWithThumbnail」みたいな構造体を新たに用意し、それで置き換えてもらうのが良いかと思います

2023-12-05 11:46 UTC, azbcww commented
確認ありがとうございます！
他の場所でも使われているの失念してました．．．
変更したので時間あるときに確認お願いします！

2023-12-07 20:26 UTC, logica0419 commented on repository/gorm/stamp.go
> +		_, ok := tm[stamp.FileID]
@motoki317 
本番環境から必要なデータだけ持ってきて、ローカル環境でloadFilteredStampsの時間を測りました

map化アリ
```
-------------------------------------------------
process time: 94.097071ms
-------------------------------------------------
2023-12-07T20:24:16.531Z        INFO    router.access_log       middlewares/access_logging.go:27        304 | 100.427362ms | GET /api/v3/stamps?type=unicode 0
-------------------------------------------------
process time: 93.238816ms
-------------------------------------------------
2023-12-07T20:24:16.553Z        INFO    router.access_log       middlewares/access_logging.go:27        304 | 109.906903ms | GET /api/v3/stamps?type=original 0
```
map化ナシ
```
-------------------------------------------------
process time: 90.35107ms
-------------------------------------------------
2023-12-07T20:21:41.542Z        INFO    router.access_log       middlewares/access_logging.go:27        304 | 96.463761ms | GET /api/v3/stamps?type=unicode 0
-------------------------------------------------
process time: 103.239511ms
-------------------------------------------------
2023-12-07T20:21:41.565Z        INFO    router.access_log       middlewares/access_logging.go:27        304 | 119.139162ms | GET /api/v3/stamps?type=original 0
```

試行によって誤差はありますが、5回くらいやって真ん中っぽそうだったものを持ってきています
正直誤差の範囲な気がしていて、これなら可読性を重視した方がいいかなと僕は思いますが、どうでしょうか？

2023-12-08 02:25 UTC, motoki317 commented on repository/gorm/stamp.go
> +		_, ok := tm[stamp.FileID]
この結果は内部のキャッシュ処理は抜いてありますかね？
気になったので少し抜き出したbenchmarkを書いてみましたが、僕の懸念はこういうことです↓
https://gist.github.com/motoki317/3c68a8359694f1fb48e29d524b76d785

本番のn=7400程度だと6ms程度で終わるようですが、試しにn=20000などに変えると45msに、n=50000だと300ms以上に跳ね上がります。
(さらに、この結果はわりと最近の強いCPU上の結果というのも留意が必要です)

僕の結論を言うと: このように増え続けるデータに対する計算で、いくらGo内部の処理とはいえ、O(N^2), n >= 1000程度以上は気にしましょう。
サブクエリでO(N^2)やってるslow queryと論理は同じです。

それに、僕の意見ですがこの程度で可読性が下がることは無いと思います。このように「hash mapを使わないとO(N^2)になってしまうから、mapにしてから計算する」はどんなプログラムでも頻出するパターンですし、そんなに読みにくいことは無いはずです。
~~ただ、変数名はもう少し読みやすくしたほうが良さそうですが~~ してあった

2023-12-08 03:48 UTC, logica0419 approved these changes
LGTM！
一回ほぼ0からの実装し直しを挟んでしまって申し訳なかったです。もうちょっと早く言えれば良かったなと思っています…
結構重めの実装だったと思いますが、完走してくれてありがとう！
今後もよろしくお願いします〜

2023-12-08 03:48 UTC, logica0419 commented on repository/gorm/stamp.go
> +		_, ok := tm[stamp.FileID]
そこまで丁寧に証拠提示されちゃったらぐうの音も出ないですね…
考えを改めます、ありがとうございます

ある程度詳しい人なら可読性下がらない、は確かにな…という感じがするので、今回はこのロジックで行きましょう

2023-12-08 05:31 UTC, azbcww commented
何度も確認ありがとうございました！

2023-12-08 05:44 UTC, merged