elastic search v8にアップデート
traPtitech/traQ pull request #2126
Opened 2023-12-03 03:40 UTC by ikura-hamu

elasticsearchの設定ファイル(elasticsearch.yml)をbind mountすると動かないので、compose.ymlで環境変数から指定しています。
参考: https://discuss.elastic.co/t/when-mounting-elasticsearch-yml-docker-displays-device-or-resource-busy/300981
elasticsearch.ymlは残してあるのですが、消しちゃってもいいですか？

動作確認は下のように行いました。
1. v7(master)の状態でいくつかメッセージを投稿して、esにデータが入ることを確認
2. v8(このブランチ)にして、`make up`
3. メッセージを検索して問題ないことを確認
4. メッセージを投稿して問題ないことを確認

go-elaasticsearchのv8からは[typedapi](https://pkg.go.dev/github.com/elastic/go-elasticsearch/v8@v8.11.1/typedapi)といういい感じに型がついたAPIクライアントもあるのですが、
- メモリリークでたまにtraQが落ちていてそこそこ影響があるし、対応が遅くなってしまったので早めにやりたい。
- バグったときにtypedapiにしたことによるバグなのかesを上げたことによるバグなのかわかりにくい。
のでこれへの書き換えはまた別の機会でいいでしょうか？

2023-12-03 03:46 UTC, motoki317 commented on compose.yaml
> -      - ./dev/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
この元ファイルは消さなくてもいいんですか？

2023-12-03 03:49 UTC, ikura-hamu commented on compose.yaml
> -      - ./dev/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
これが議論中でそのうち使えるように戻るかもしれなかったので残すか迷ってます。
https://github.com/elastic/elasticsearch/issues/85463#issuecomment-1229264396

2023-12-04 11:09 UTC, logica0419 commented on compose.yaml
> -      - ./dev/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
正直、ほぼ中身無いから消しちゃっていいかなと思います
開発環境なので別にその辺の体裁気にすることないかなぁと

2023-12-04 14:16 UTC, pikachu0310 commented
> go-elaasticsearchのv8からは[typedapi](https://pkg.go.dev/github.com/elastic/go-elasticsearch/v8@v8.11.1/typedapi)といういい感じに型がついたAPIクライアントもあるのですが、
> - メモリリークでたまにtraQが落ちていてそこそこ影響があるし、対応が遅くなってしまったので早めにやりたい。
> - バグったときにtypedapiにしたことによるバグなのかesを上げたことによるバグなのかわかりにくい。
> 
> のでこれへの書き換えはまた別の機会でいいでしょうか？

賛成です。そこそこ重そうですし、別でやるべきだと思います。

2023-12-04 14:17 UTC, pikachu0310 submitted a review, later dismissed

2023-12-04 16:31 UTC, logica0419 requested changes
実装は良さそうです！ReadSeekerへの変更に対応するの、ありがとうございます
compose.yamlの方に少し修正して欲しいポイントがあるので、お願いします

2023-12-04 16:31 UTC, logica0419 commented on compose.yaml
> +      - xpack.security.enabled=false
これはhttpsに関係ないので、コメントの上に書いてくれると嬉しいです
(認証の設定をするときに消します)

2023-12-04 16:31 UTC, logica0419 commented on compose.yaml
> +      - xpack.security.audit.enabled=false
audit設定はfalseにしなくても動いたんですが、これ追加した意図ってなんかありますか？
何か重要な理由が無い限り、本番環境とできるだけ同じ設定で動かしたいので消してもらえると嬉しいです

2023-12-04 16:31 UTC, logica0419 commented on compose.yaml
> +      - xpack.security.transport.ssl.enabled=false
ここの環境変数のところ、他のserviceと記法を統一したいので、「`{key}: {value}`」の形に直してもらえるととても助かります
(keyは小文字のままで大丈夫そうでした)

2023-12-04 16:39 UTC, logica0419 commented on compose.yaml
> +      - xpack.security.transport.ssl.enabled=false
ssl.enabledをfalseにしなくてもこっちの環境だと通ったんですけど、↑の3つの設定どこから引っ張ってきました？
元があれば教えてほしい & そっちの環境でエラー出るなら教えてほしいです

2023-12-04 17:12 UTC, logica0419 commented
あと、typedapiへの書き換えはikura-hamuくんの提案通り別PRでやってもらえると嬉しいです

2023-12-07 05:11 UTC, ikura-hamu commented on compose.yaml
> +      - xpack.security.transport.ssl.enabled=false
これを参考に設定しました。
https://blog.goo.ne.jp/dak-ikd/e/50e75332922a75be1391eace5c479141
この行を消しても動いたので消しておきます。

2023-12-07 05:12 UTC, ikura-hamu commented on compose.yaml
> +      - xpack.security.audit.enabled=false
理由はこれと同じです。こちらも動いたので消しておきます。
https://github.com/traPtitech/traQ/pull/2126#discussion_r1418363920

2023-12-07 05:15 UTC, ikura-hamu commented on compose.yaml
> +      - xpack.security.enabled=false
認証の設定をするときっていうのは、本番環境のesをいじるってことですか？

2023-12-07 05:19 UTC, ikura-hamu commented
@logica0419 @pikachu0310 
修正したので、再確認お願いします。

2023-12-07 05:56 UTC, logica0419 commented on compose.yaml
> +      - xpack.security.enabled=false
それもそうなんだけど、traQ側からユーザー名とパスワードを渡して認証する機能をつけるってことですね

2023-12-07 06:07 UTC, logica0419 approved these changes
LGTM
elastic.yml消し忘れてるけど、まぁそれはどっちでもいいか

2023-12-07 13:41 UTC, merged