プライベートチャンネル周りの実装
traPtitech/traQ pull request #217
Opened 2018-03-30 10:16 UTC by masutech16

## 実装したもの
+ POST users/{userID}/messages DMを送る(channelができてない場合は作る
+ GET users/{userID}/messages DMを取得する(channelがない場合はエラーを返す

## 見てほしいところ
+ URIが`channels/{userID}/messages`のほうがいい気がするんですけどどうでしょう
+ クエリがもっといい感じになりそうなのでそこら辺の指摘が欲しいです

2018-03-31 03:33 UTC, tohutohu commented
channelがない場合はから配列を返すほうが良いと思います
クライアントとしてはchannelがないのとメッセージが存在しないことは同じなので

2018-03-31 12:57 UTC, wtks reviewed
`/channels/{userID}/messages`にしてしまう案があるけど、↑の空配列を返すところを直せばとりあえずいいと思う。

2018-03-31 13:09 UTC, tohutohu commented
/channels/{userID}/messagesにしてしまう案
↑でいいと思うんですけど実装が面倒になるとか何か問題がありますかね？
UUIDがかぶるということはないでしょうけど

2018-04-01 04:25 UTC, masutech16 commented
とりあえず上の指摘全部直しました

2018-04-01 10:37 UTC, tohutohu requested changes
どうにかしてchannelタグのmessagesで統一的に扱えるようにしたいですね
channelにisDMを生やすとか？

2018-04-01 10:37 UTC, tohutohu commented on main.go
> +	api.POST("/channels/:userID/messages", router.PostPrivateMessage, requires(permission.PostMessage))
これって区別つくんですか？

2018-04-01 10:37 UTC, tohutohu commented on main.go
> +	api.POST("/channels/:userID/messages", router.PostPrivateMessage, requires(permission.PostMessage))
たぶん区別できないので☓

2018-04-01 17:57 UTC, masutech16 commented
privateチャンネルは`private9-9dwb-4evo-3rks-we6dcsodkrci`というIDを親に持つようになりました
これでDMかどうかを区別する必要がなくなったのでDM用のAPIは削除されました

2018-04-02 02:37 UTC, wtks commented
そのIDも一応UUIDの規格に合わせてほしい(`[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}`, `xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx`←Variantは4で、yは89ABのどれか)

2018-04-02 08:28 UTC, tohutohu approved these changes

2018-04-02 08:30 UTC, merged