Elastic searchのbulk indexerのメモリリーク修正
traPtitech/traQ pull request #2190
Opened 2024-01-12 03:50 UTC by ikura-hamu

fix: #2172 
関数に切り出して、deferでindexerをCloseするようにした。

2024-01-12 04:16 UTC, motoki317 approved these changes, later dismissed
テストはあまり書かれていない箇所ですが、動作確認（新規作成、更新、削除それぞれのパスを実行させてみる）は取れていますか？

そうならば、リークの動作は本番以外ではなかなか再現難しいと思うので、早めにリリースして様子を見るのが良いと思います

2024-01-12 04:16 UTC, motoki317 commented on service/search/es_sync.go
> +	})
これとsyncDeletedMessagesでも捨ててるのってerrorですか？
ならちゃんとhandlingしても良いと思う
```suggestion
	bulkIndexer, err := esutil.NewBulkIndexer(esutil.BulkIndexerConfig{
		Client: e.client,
		Index:  getIndexName(esMessageIndex),
	})
	if err != nil {
		return err
	}
```

2024-01-12 04:29 UTC, ikura-hamu commented on service/search/es_sync.go
> +	})
errorです。確かにハンドリングした方が良さそうなので、します。

2024-01-12 04:31 UTC, ikura-hamu commented
> テストはあまり書かれていない箇所ですが、動作確認（新規作成、更新、削除それぞれのパスを実行させてみる）は取れていますか？
> 
> そうならば、リークの動作は本番以外ではなかなか再現難しいと思うので、早めにリリースして様子を見るのが良いと思います

2024-01-12 04:35 UTC, ikura-hamu commented
まちがってcloseしちゃった。
手元の動作確認はして、追加、編集、削除ができてることは確認しました。

2024-01-12 04:36 UTC, motoki317 approved these changes, later dismissed

2024-01-12 17:48 UTC, logica0419 requested changes
ありがとう！だいぶ理想的な解決方法になっていると思います。ありがたい。
いくつか指摘したので、確認の方お願いします

2024-01-12 17:48 UTC, logica0419 commented on service/search/es_sync.go
> +			err = fmt.Errorf("error in bulk index: %w.\nerror in closing bulk indexer: %w", err, er) //無名関数の戻り値を名前付きにしているので、このerrが返る。
> //無名関数の戻り値を名前付きにしているので、このerrが返る。

これは流石に書かなくてもわかるかな…と思うので、消しておいてもらえると嬉しいです

2024-01-12 17:48 UTC, logica0419 commented on service/search/es_sync.go
> +		er := bulkIndexer.Close(context.Background())
`er`ってネーミング一般的なのかどうかちょっと疑問です
`closeErr`とかにしてもらった方がわかりやすいかも…と思ってます

2024-01-12 17:48 UTC, logica0419 commented on service/search/es_sync.go
> +		er := bulkIndexer.Close(context.Background())
上同様

2024-01-12 17:48 UTC, logica0419 commented on service/search/es_sync.go
> +	}
`count`が0でも`bulkIndexer.Close()`は走るようになったので、`count`が意味を為さなくなっている気がします
`Add()`した数が0で`Close()`してもバグらないようなら大丈夫なので、冗長な`count`の処理を消しておいてもらえると嬉しいです

2024-01-13 05:11 UTC, ikura-hamu commented on service/search/es_sync.go
> +	}
手元で0でも大丈夫なことが分かったので、消します。

2024-01-13 07:47 UTC, logica0419 approved these changes
ありがとう！完璧です！
これで治れば良いな…

2024-01-13 08:08 UTC, ikura-hamu commented
マージしていいですか？

2024-01-13 08:12 UTC, logica0419 commented
いいよ

2024-01-13 08:13 UTC, merged