USER_ACTIVATEDイベントを追加
traPtitech/traQ pull request #2266
Opened 2024-01-16 14:22 UTC by mehm8128

close https://github.com/traPtitech/traQ/issues/2030

2024-01-16 14:49 UTC, logica0419 commented
1. 手元環境でBotを作る
1. Botにactivate userイベントをsubscribeさせる
  - 上2つはURL直だたきになるかも
  - bot-consoleをcompose内で起動しても良いとは思う
1. Botのイベント送信先URLをダミーサーバーに当てる
  - 一応bot_debuggerというコンテナがその役割を果たしている
  - Postmanでも作れるらしい
    - https://qiita.com/kanon47/items/b9a08b7314732f6d2510
1. 手元環境で凍結・解除をしてみて正常にリクエストが飛ぶか確かめる

って感じでデバッグはできると思います
ちょっと大変だけど…頑張ってみてもらえると嬉しいです

2024-01-16 14:52 UTC, logica0419 commented
bot_debuggerにもともと全てのログが送られている可能性もある気はするので、ちょっと一回bot_debuggerの方確認してもらってからの方がいいかもしれないです

2024-01-16 21:28 UTC, mehm8128 commented
分かりました、やってみます

2024-01-22 07:12 UTC, mehm8128 commented
bot_debuggerの方でやり方が分からなくて(http modeでやったのですが、activateが上手くいかなかったりendpointにlocalhostのurlを指定できなかったり)、結局postmanでやり、ちゃんと受け取れていることが確認できました
![image](https://github.com/traPtitech/traQ/assets/83744975/31b7736a-d006-4c52-aedc-d74ebad6e958)

2024-01-22 20:44 UTC, logica0419 reviewed
ありがとう！実装に不備はなさそうです！素晴らしい
ちょっとだけリファクタのお願いしたいのでそれだけお願いします

2024-01-22 20:44 UTC, logica0419 commented on repository/gorm/user.go
>  			}
ここ、switch文使った方が趣旨がわかりやすそうな気がしますね

2024-01-22 20:44 UTC, logica0419 commented on repository/gorm/user.go
>  				Name: event.UserUpdated,
ちょっと今回の変更範囲にあまり関係なくて申し訳ないんだけど、ここもswitch文使ってまとめられると見やすくなるかと思うので、お願いしたいです
あとif changedのとこでifネストが無駄に深くなってるの気になっちゃったので、良ければそれも直してもらえると助かります…

2024-01-23 05:28 UTC, logica0419 requested changes
一応確認
activatedの時UserUpdateイベントが発行されていたのが今後発行されなくなる(クライアントにWebSocketで行かなくなる)のだけれど、そこに関しては大丈夫？

2024-01-23 05:28 UTC, logica0419 commented on repository/gorm/user.go
>  	)
前のレビューで気づけなくて申し訳ない
ここでvarが2連になるのキモいかな〜と思ったので、uの定義を下の括弧に含めてもらえると良い感じになるかなと思います

2024-01-23 05:34 UTC, mehm8128 commented
>activatedの時UserUpdateイベントが発行されていたのが今後発行されなくなる(クライアントにWebSocketで行かなくなる)のだけれど、そこに関しては大丈夫？

これちょっと考えていて、`USER_ACTIVATED`イベントを追加でlistenするようにすればいいかなって思ってたんですけど、やっぱり`USER_UPDATED`ももらえるようにした方がよさそうなので直します
直すとしたら`activate`のcaseに
```go
r.hub.Publish(hub.Message{
			Name: event.UserUpdated,
			Fields: hub.Fields{
				"user_id": id,
			},
		})
```
を追加することになりそうですかね？defaultと重複しちゃうので上手くまとめられるならまとめたい気がしてます

2024-01-23 05:47 UTC, mehm8128 commented
調べてみたら`fallthrough`でbreakしないようにできるんですね
`activate`のcaseで`fallthrough`すればdefaultのも実行できそうですが、上で書いたように普通に追加するのとどっちがよさそうですか？

2024-01-23 06:42 UTC, mehm8128 commented
一旦fallthroughする方針でやってみました

2024-01-23 16:17 UTC, logica0419 approved these changes
LGTM！
対応ありがとう～

2024-01-23 23:39 UTC, merged