PATCH /users/me の修正
traPtitech/traQ pull request #229
Opened 2018-04-02 17:11 UTC by masutech16

displayName, password, emailが変更できるようになった。
displayNameのみの変更の時はパスワードは不要で、それ以外の項目をいじるときは変更前のパスワードを要求する

2018-04-02 18:43 UTC, tohutohu requested changes

2018-04-02 18:43 UTC, tohutohu commented on router/users.go
> +		ExPassword  string `json:"exPassword"`
このexってなんですか？

2018-04-02 18:43 UTC, tohutohu commented on router/users.go
> +	user.Email = req.Email
これだとメールアドレスかパスワードどちらかだけ変更したい場合でも、両方入れないといけなくなって面倒なのでリクエストで値が入っているものだけ変更するようにしてください

2018-04-02 18:43 UTC, tohutohu commented on router/users.go
> +		Password    string `json:"password"`
validatorでバリデーションしてください(passwordは使用文字、メールはメール形式で)

2018-04-02 18:43 UTC, tohutohu commented on router/users.go
> +	user.Email = req.Email
UIは自分の登録メールアドレスを知る方法ないですよね？

2018-04-03 01:49 UTC, masutech16 commented on router/users.go
> +		Password    string `json:"password"`
`user.Update()`内部でvalidateされているから不要だと思います。

2018-04-03 01:50 UTC, masutech16 commented on router/users.go
> +		ExPassword  string `json:"exPassword"`
ex-で"以前の"という意を表す接頭辞なので、それから来ています
なんか今調べたらものに対してはformerを使うのが一般的らしいので、気になるようなら変えます(短いし個人的にはこのままでよいと思っている

2018-04-03 02:03 UTC, tohutohu commented on router/users.go
> +		ExPassword  string `json:"exPassword"`
なるほど、理由を聞きたかっただけなのでいいようにしてください

2018-04-03 02:03 UTC, tohutohu commented
OKになったらコメントほしい

2018-04-03 02:08 UTC, masutech16 commented
テスト通った

2018-04-03 02:14 UTC, tohutohu approved these changes

2018-04-03 02:14 UTC, merged