client credentials grantを利用できるように
traPtitech/traQ pull request #2433
Opened 2024-05-22 17:03 UTC by kyosu-1

2024-06-21 07:44 UTC, ras0q commented on service/rbac/role/client.go
> +}
knoQで使いたいのでGetUsersやGetUserGroupsがあると助かります:pray:
Draftで仮置きしてるだけかもですが

2024-06-21 07:45 UTC, hijiki51 requested changes, later dismissed

2024-06-21 07:45 UTC, hijiki51 commented on service/rbac/role/client.go
> +// Cliet Clientロール (for OAuth2 client credentials grant)
``` suggestion
// Client Clientロール (for OAuth2 client credentials grant)
```

2024-06-21 10:27 UTC, kyosu-1 commented on service/rbac/role/client.go
> +}
GetUsersとGetUserGroupsのAPIはpermission.GetUserのRoleとpermission.GetUserGroupを持っていれば叩けますね。(APIと一対一対応ではなく、一つのpermissionが複数のAPIを対象として許可しています。)
ref: 
https://github.com/traPtitech/traQ/blob/4ac16404c3a12e44ef1503b0d8cd9b2899deeede/router/v3/router.go#L88
https://github.com/traPtitech/traQ/blob/4ac16404c3a12e44ef1503b0d8cd9b2899deeede/router/v3/router.go#L281

一応permissionのListは https://github.com/traPtitech/traQ/blob/4ac16404c3a12e44ef1503b0d8cd9b2899deeede/service/rbac/permission/permission.go#L47 ここの一覧として載っています。

2024-06-21 10:53 UTC, kyosu-1 commented
安全性を高めるなら

```
```

2024-06-21 11:15 UTC, motoki317 commented on service/rbac/role/client.go
> +}
少なくない？そんなことない？
自身のユーザーに関連しないものは許可してよさそう
https://github.com/traPtitech/traQ/blob/master/service/rbac/role/read.go

2024-06-21 11:15 UTC, motoki317 commented on service/rbac/role/role.go
> +		Client: &systemRole{
新しくrbacのロールとpermission一覧を更新するときはmigrationが必須です

2024-06-21 11:20 UTC, kyosu-1 commented on service/rbac/role/role.go
> +		Client: &systemRole{
memo:
https://github.com/traPtitech/traQ/blob/4ac16404c3a12e44ef1503b0d8cd9b2899deeede/migration/v35.go
https://github.com/traPtitech/traQ/blob/4ac16404c3a12e44ef1503b0d8cd9b2899deeede/migration/current.go#L48

ここら辺と同じように

2024-06-21 20:05 UTC, kyosu-1 commented on service/rbac/role/client.go
> +}
見落としあるかもしれませんが、確認した限りはこれら以外のpermissionで許可されるエンドポイントの中には `getRequestUserID` が 含まれてそうな感じでした。
e.g. permission.GetMessage で許可されるエンドポイントの中に`GetDirectMessages` が含まれる

https://github.com/traPtitech/traQ/blob/4ac16404c3a12e44ef1503b0d8cd9b2899deeede/router/v3/messages.go#L344

https://github.com/traPtitech/traQ/blob/4ac16404c3a12e44ef1503b0d8cd9b2899deeede/router/v3/router.go#L97

permissionで許可するエンドポイントの対応関係を上手く考え直せば与えられる許可は増やせそうですが、影響範囲大きくなるのでひとまずこれぐらいのpermissionでも良いかなと思ってます。

2024-06-21 20:56 UTC, motoki317 commented on service/rbac/role/client.go
> +}
うーん、なるほど あまりきめ細やかに制御されてなくて難しいんですね
そうしたらその権限の制御のやり方を考え直す(より細やかにする)か、client credentials grantにそもそもユーザーをどうにかして紐づけるか、とかを考えたいところですね

少なくとも今やらない(できなかった)のなら、その理由をコメントとかで書いておくべきだと思います

2024-06-21 22:10 UTC, kyosu-1 commented on service/rbac/role/client.go
> +}
Issue立てつつコメント残す形にしました

2024-10-19 14:44 UTC, ras0q approved these changes, later dismissed

2025-05-02 06:01 UTC, Takeno-hito approved these changes
LGTM です 機能の詳細はレビューできてないですが、既存の機能などに影響はでないのでえいやでマージします

2025-05-02 12:06 UTC, merged