Make NewMessageCounter async
traPtitech/traQ pull request #2464
Opened 2024-06-24 09:29 UTC by nagaeki

2024-07-01 23:18 UTC, pikachu0310 requested changes
レビュー遅くてごめんなさい！
貢献ありがとうございます！かなりいい感じなのですが、初期化を待つ処理が無いので、初期化中にGETされてしまうと返す値がズレてしまいそうです。惜しいです！

こうすればできそう～という、僕が思いついた簡易的な実装を書いたので、参考にして修正してみて下さい～！

2024-07-01 23:18 UTC, pikachu0310 commented on service/counter/message.go
> +)
以下の様にチャネルも定義して、初期化の完了を他のゴルーチンに通知する事で上手く実装出来そうです。

```suggestion
var (
	messagesCounter prometheus.Counter
	initOnce        sync.Once
	initDone        = make(chan struct{})
)
```

2024-07-01 23:18 UTC, pikachu0310 commented on service/counter/message.go
>  		for range hub.Subscribe(1, event.MessageCreated).Receiver {
初期化チェックを追加
```suggestion
	go func() {
		<-initDone
		for range hub.Subscribe(1, event.MessageCreated).Receiver {
```

以下の様に、Get() の所にも追加するべき。
```
func (c *messageCounterImpl) Get() int64 {
	<-initDone
	c.RLock()
	defer c.RUnlock()
	return c.count
}
```

2024-07-01 23:18 UTC, pikachu0310 commented on service/counter/message.go
> +		})
初期化が完了したことを通知する
```suggestion
			})
			messagesCounter.Add(float64(counter.count))
			close(initDone)
		})
```

2024-07-01 23:18 UTC, pikachu0310 commented on service/counter/message.go
> +		once.Do(func() {
(少し変数名を変えたので、変更)
```suggestion
		initOnce.Do(func() {
```

2024-07-01 23:18 UTC, pikachu0310 commented on service/counter/message.go
> +			panic(err)
panic ではなく、エラーを返すようにしたいな～
initError みたいな変数を用意して格納させるとかで良さそう。

2024-07-23 22:09 UTC, pikachu0310 commented
機能面は良さそうです！
ただ、@motoki317 の https://q.trap.jp/messages/e55d6ed9-ad4e-42bc-bce8-f65844b3f34d を参考にすると、かなりコードを簡素にかつ分かりやすくできると気づいたため、リファクタリングをしました。

具体的には、
- sync.RWMutex から sync/atomic にすることで、軽量でより読みやすくしました。
- 初期化とカウンターの増加部分を関数で分離しました。
- Get() と inc() の最初に sync.Once を呼び出すことで、初期化が保証されるようにして、sync.Once の特徴を上手く活かす形にしました。
- count をグローバル変数にして、不要な変数を削除しました。

2024-07-24 01:54 UTC, motoki317 requested changes

2024-07-24 01:54 UTC, motoki317 commented on service/counter/message.go
> +	}
結局これでは非同期にはなりません...

sync.Onceは、Doを呼んだらそれが返ったときには、ただ一度だけ中の関数の実行が終了しているという性質を持ちます。
↓を参考にしたり、もしよかったらsync.Onceの実装の中身も覗いてみてください。
https://q.trap.jp/messages/50247bdf-5920-4bfa-8a12-c4d789b74792
https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/sync/once.go;l=18
(sync.OnceFuncもだいたい同じで、こちらの方が今回の場合は使いやすいかも)

この性質と、promauto.CounterFuncで値をこちら側でコントロールできる性質を活かして、立ち上がり時はブロックしないけど、値を取得するときには初期化が終了していることを表現してみてください。

2024-10-19 14:27 UTC, kaitoyama commented
開発の時間が取れないとのこと&非同期を達成できていないのでclose

2024-10-19 14:27 UTC, closed without merging