Feat: add API to get channel info from channel path and get channel path from channel id
traPtitech/traQ pull request #2476
Opened 2024-07-03 10:36 UTC by Eraxyso

Solves Issue #2356

2024-07-23 22:27 UTC, pikachu0310 commented
遅れててごめんなさい、近いうちに見ます。

2024-10-26 11:52 UTC, ramdos0207 requested changes
`/channels`の実装は完璧です！ただ、`/channels/{channelID}/path`の方は数カ所気になるポイントがあったのでコメントしました。確認をお願いします！

2024-10-26 11:52 UTC, ramdos0207 commented on router/v3/channels.go
> +	return c.JSON(http.StatusOK, channelPath)
`channelPath`が`string`型なので、OpenAPIの型定義と異なるものが帰ってきてしまいます。

2024-10-26 11:52 UTC, ramdos0207 commented on docs/v3-api.yaml
> +      description: 指定したチャンネルのパスを取得します。
質問：`/channels/{channelID}`や`/channels`にpathの情報を含めるのでは無く、別のエンドポイントとして実装することになった理由を教えて欲しいです！

2024-10-26 11:52 UTC, ramdos0207 commented on docs/v3-api.yaml
> +
nits:余計な空行が入っています（入っていた方が読みやすい気もしますが、現状だとファイル全体を通して余計な空行は入れないことにしているみたいなので、合わせた方がいいかも？）

2024-10-26 11:52 UTC, ramdos0207 commented on docs/v3-api.yaml
> +      - $ref: '#/components/parameters/channelIDInPath'
大文字小文字が違うのでエラーが出ていそうです
```diff
-      - $ref: '#/components/parameters/channelIDInPath'
+      - $ref: '#/components/parameters/channelIdInPath'
```

2024-11-02 20:18 UTC, Eraxyso commented on docs/v3-api.yaml
> +      description: 指定したチャンネルのパスを取得します。
/channels/{channelID} と /channelsはチャンネル情報を返しますが、その中にはチャンネルパスが含まれていません。チャンネルパスをチャンネル情報に含めることは作業量が大きく、パスを利用するケースもそれほど多くないと考えたため、/channels/{channelID}/pathに実装しました。

2024-11-02 21:06 UTC, Eraxyso commented
ご指摘いただいたところを修正しました

2024-11-03 00:13 UTC, ramdos0207 commented on docs/v3-api.yaml
> +      description: 指定したチャンネルのパスを取得します。
なら良さそうです！

2024-11-03 00:14 UTC, ramdos0207 approved these changes

2024-11-03 00:15 UTC, ramdos0207 commented
完璧です！マージします

2024-11-03 00:15 UTC, merged