BotのPACHにbioフィールドを追加
traPtitech/traQ pull request #2483
Opened 2024-07-13 11:39 UTC by UnABC

2024-07-16 00:18 UTC, Takeno-hito reviewed
LGTM traQ メンバーからレビューをもらってください！

2024-07-16 00:18 UTC, Takeno-hito commented
close: #2035

2024-07-16 14:58 UTC, kaitoyama requested changes
ありがとうございます!
レビューしましたので、確認お願いします!

2024-07-16 14:58 UTC, kaitoyama commented on router/v3/bots.go
> +		vd.Field(&r.Bio, vd.RuneLength(0, 1000)),
これに対応するtraQ/router/v3/bots_test.go内でのテストを作成した方が良いと思います

2024-07-16 14:58 UTC, kaitoyama commented on docs/v3-api.yaml
> +          maxLength: 1000
書き換えているcomponentが違いそうです。
BotDetailを書き換えているが正しくはPatchBotRequestだと思います

2024-07-23 21:00 UTC, pikachu0310 approved these changes
LGTMです！(レビューリクエストは飛んできてないのですが、既に修正されてそうなので見ました！)

2024-07-23 21:01 UTC, pikachu0310 approved these changes

2024-07-23 21:52 UTC, kaitoyama approved these changes
TY!

2024-07-23 21:52 UTC, merged