チャンネル機能の実装#21
traPtitech/traQ pull request #34
Opened 2017-12-04 09:22 UTC by tohutohu

2017-12-04 09:22 UTC, tohutohu commented
#21

2017-12-05 09:15 UTC, tohutohu commented
大方実装できたのでレビューお願いします  
エラーやバリデーションをこれから追加していく予定です

2017-12-05 09:16 UTC, kaz commented
いまのmasterにリベースしてほしい

2017-12-11 09:13 UTC, kaz requested changes

2017-12-11 09:13 UTC, kaz commented on model/channels.go
> +	IsHidden  bool   `xorm:"bool not null"`
`IsVisible`にしたい

- 名称の曖昧性除去
- 真偽反転

db_schema.mdも

2017-12-11 09:13 UTC, kaz commented on model/channels.go
> +
NameのValidate

- 英数と`-_`
- 20文字

2017-12-11 09:13 UTC, kaz commented on model/channels.go
> +	channel := new(Channels)
`&Channels{}`

2017-12-11 09:13 UTC, kaz commented on model/channels.go
> +type Channels struct {
`Channel`
http://gobook.io/read/github.com/go-xorm/manual-en-US/chapter-02/3.tags.html

2017-12-11 09:13 UTC, kaz commented on model/channels.go
> +	channel := Channels{Id: channelId}
ポインタレシーバ`Exists()`にしましょう

あと、`userId`を取って、不可視のチャンネルに対してはfalseを返すのが妥当と思いました

2017-12-11 09:13 UTC, kaz commented on model/channels.go
> +	err := db.Join("LEFT", "users_private_channels", "users_private_channels.channel_id = channels.id").Where("(is_public = true OR user_id = ?) AND is_deleted = false", userId).Find(&channelList)
`GetChannels`とかシンプルな名前のほうが良さそう
非表示/表示で取得できるようにする？

2017-12-11 09:13 UTC, kaz commented on model/channels.go
> +	// err := db.Join("LEFT", "users_private_channels", "users_private_channels.channel_id = channels.id").Where("is_public = true OR user_id = ?", userId).Cols("id").Find(&channelIdList)
ポインタレシーバ`Children`にしましょう

2017-12-11 09:13 UTC, kaz commented on router/channel.go
> +	responseBody.Message = message
echoにエラーハンドラを渡せるので、`router/utils.go`とかに定義して、ソレを使う形にしましょう。
https://echo.labstack.com/guide/error-handling

c.Errorしてたり、messageResponseしてたりいろいろですが、
messageResponseするのをやめて、ハンドラからerrorが帰ったら↑のエラーハンドラ内で処理して返す形。
あと、エラーメッセージは英語で

echo.NewHTTPErrorを使うと、エラーコードも上手く返せるはずです！

2017-12-11 09:13 UTC, kaz commented on router/channel.go
> +	}
106行目からここまで、1行で書ける

```go
newChannel := &models.Channels{CreatorId: userId, Name: requestBody.Name, IsPublic: requestBody.ChannelType == "public"}
```

2017-12-11 09:13 UTC, kaz commented on router/channel.go
> +		c.Error(err)
くっつけたい
```go
if err := newChannel.Create(); err !=nil {
```

2017-12-11 09:13 UTC, kaz commented on router/channel.go
> +		// TODO:通知周りの実装
newChannel.IsPublicを使うほうが少しエコ

2017-12-11 09:13 UTC, kaz commented on router/channel.go
> +}
ここエラー握り潰さない方が良い

他のハンドラも同様

2017-12-11 09:13 UTC, kaz commented on router/channel.go
> +	return nil
ここ、異常系がifの中で、正常系はその外(elseなし)の方が良いです。
```go
if !requestBody.Confirm {
```

2017-12-11 09:13 UTC, kaz commented on router/channel.go
> +	sess, err := session.Get("sessions", c)
〜〜Hanlderの**Handler**を全部なくしてよさそう
冗長だし

2017-12-12 07:28 UTC, tohutohu commented on router/channel.go
> +	responseBody.Message = message
下のIssueで解決ということでいいですか？
https://github.com/traPtitech/traQ/issues/37

2017-12-12 07:29 UTC, tohutohu commented
修正しました

2017-12-21 11:25 UTC, kaz submitted a review, later dismissed
LGTM :)

2017-12-23 13:07 UTC, closed without merging