MessageタグのAPIの実装
traPtitech/traQ pull request #36
Opened 2017-12-11 08:19 UTC by masutech16

2017-12-11 09:34 UTC, kaz requested changes
こっちのコメントも軽く眺めておいてください！
https://github.com/traPtitech/traQ/pull/34

あと、`go fmt ./...`かけてからpushしてくれると嬉しい

2017-12-11 09:34 UTC, kaz commented on model/messages.go
> +	var messageList []*Messages
これ、`Channel`構造体のレシーバとして実装したほうが良さそう
cc. @tohutohu

2017-12-11 09:34 UTC, kaz commented on router/error.go
> +	res.message = message
エラー処理について↓
https://github.com/traPtitech/traQ/pull/34#discussion_r156010930

2017-12-11 09:34 UTC, kaz commented on router/messages.go
> +	message.ChannelId = channelId
ここ一行で書けます
```go
message := &model.Messages{UserId: userId, Text: post.Text, ChanneId: channelId}
```

2017-12-11 09:34 UTC, kaz commented on router/messages.go
> +	sess, err := session.Get("sessions", c)
`router/utils.go`とかに移動して、他のAPIと共通に使ったほうがいいかも
cc. @tohutohu

2017-12-11 14:46 UTC, tohutohu commented on model/messages.go
> +	var messageList []*Messages
これオフセットとか個数とかの指定は必要ないですか？

2017-12-13 00:50 UTC, masutech16 commented on model/messages.go
> +	var messageList []*Messages
それはちょっと思いました。
クエリで指定してもらう形にして、クエリがなければ今のまま全件返して、あれば指定されたもののみを返すという形が良いですかね？

2017-12-20 15:29 UTC, masutech16 commented
コメントされた内容について修正しました

2017-12-21 11:25 UTC, kaz approved these changes
LGTM :)

2017-12-25 10:07 UTC, merged