Channel
traPtitech/traQ pull request #41
Opened 2017-12-22 15:28 UTC by tohutohu

Channel周りのAPIを実装しました

2017-12-22 16:32 UTC, masutech16 requested changes
大体見ましたが眠いので見落としがありそうです。いくつか質問したのでコメントお願いします。

2017-12-22 16:32 UTC, masutech16 commented on model/channels.go
> +	UpdatedAt int    `xorm:"updated not null"`
gonicMapperを使うかどうかは統一したいです。どうしましょう

2017-12-22 16:32 UTC, masutech16 commented on model/channels.go
> +	_, err := db.Id(channel.ID).UseBool().Update(channel)
xormのengine.Idはdeprecatedになるので代わりにIDを使うとよいと思います。
[ref](https://godoc.org/github.com/go-xorm/xorm#Engine.Id)

2017-12-22 16:32 UTC, masutech16 commented on model/channels_test.go
> +	channel.IsPublic = true
```golang
channel := &channel{
    CreatorID: testUserID,
    Name: "testChannel",
    IsPublic: true,
}
```
と書いた方がぼくは好きです。どうなんでしょう。
更にこのコードを複数個所で見るのですが、makeChannelで作らない理由を知りたいです

2017-12-22 16:32 UTC, masutech16 commented on model/channels_test.go
> +		usersPrivateChannel.UserID = privateUserID
上と同様

2017-12-22 16:32 UTC, masutech16 commented on model/utils_test.go
> +	engine.DropTables("sessions", "channels", "users_private_channels")
DropTablesの引数にmessagesも入れておいてほしいです。

2017-12-22 16:32 UTC, masutech16 commented on model/utils_test.go
> +	engine.DropTables("sessions", "channels", "users_private_channels")
同様

2017-12-22 16:32 UTC, masutech16 commented on router/channels.go
> +}
ErrorHandlerを実装したのでErrorResponseの構造体はなくて大丈夫だと思います。

2017-12-22 16:32 UTC, masutech16 commented on router/channels.go
> +		}
これif節で囲っている理由が気になります

2017-12-22 16:32 UTC, masutech16 commented on router/channels.go
> +	}
単純に質問なんですが、ここで構造体宣言すると何かいいことがあったりするんですか？(上で書かない理由が気になりました

2017-12-22 16:32 UTC, masutech16 commented on router/channels_test.go
> +func TestGetChannelsHandler(t *testing.T) {
testの関数名からHandlerが消えてないです。実装の方では消したので合わせたい

2017-12-22 16:37 UTC, tohutohu commented on model/channels.go
> +	UpdatedAt int    `xorm:"updated not null"`
忘れてました
gonicを使うようにしましょう

2017-12-22 16:46 UTC, tohutohu commented on model/channels_test.go
> +	channel.IsPublic = true
これらのコードを書いた後でmakeChannelとか作ったからですね
makeChannel(Detail)を使うように変更しました

2017-12-22 16:48 UTC, tohutohu commented on router/channels.go
> +	}
ここでしか使わないからですね
他の関数で使用することがない(はず)なのでここでいいかと思いました

2017-12-22 16:52 UTC, tohutohu commented on router/channels.go
> +		}
下の方(同じfor内)で`response[ch.ParentID]`をいじってるところがあるんですが、そこで初期化されている場合があるからです。
問答無用で代入すると自身の子供のチャンネルの情報が適切に入らないことがあると思います。
これは必要な処理だと思うんですがどうでしょう

これが気持ち悪いと思うなら(自分も若干思うけど)forを直列に2個並べるといけます。
一個目で自分のことやって2個めで子供のことやる

2017-12-23 02:01 UTC, masutech16 approved these changes
良いと思います

2017-12-23 02:01 UTC, masutech16 commented on router/channels.go
> +		}
把握しました。確かに必要だと思うのでこれでよいと思います。

2017-12-23 02:47 UTC, merged