topicタグの実装
traPtitech/traQ pull request #44
Opened 2017-12-23 13:09 UTC by tohutohu

Close #42 
https://app.swaggerhub.com/apis/wtks/test/0.0.1#/topic/

2017-12-24 12:47 UTC, masutech16 requested changes
一カ所だけ変更お願いします

2017-12-24 12:47 UTC, masutech16 commented on router/topic.go
> +// GetTopic GET /channels/{channelID}/topic
このコメントの形式見やすくて良いのでこれで揃えたいかも。
良ければissue立てておきます

2017-12-24 12:47 UTC, masutech16 commented on router/topic_test.go
> +	requestBody := putTopic{
構造体宣言するときは&hoge{}の形式にそろえましょう。(現状でも動くけれど

2017-12-25 00:48 UTC, tohutohu commented on router/topic_test.go
> +	requestBody := putTopic{
ここは値としてしか使わないので&なくてもいいかな〜と思ったんですけどどうでしょう
Goの場合ポインタも値も同じように扱えるので大きな問題はないと思いますが

2017-12-25 08:09 UTC, masutech16 approved these changes

2017-12-25 08:15 UTC, merged