Pin
traPtitech/traQ pull request #50
Opened 2017-12-25 12:23 UTC by yasu0001

2017-12-30 12:56 UTC, kaz requested changes
PUSHする前に、`go fmt ./...`していただけるとうれしいです！

2017-12-30 12:56 UTC, kaz commented on model/pins.go
> +  pinnedMessage.ChannelId = channelId
```diff
- pinnedMessage := &Pins{}
- pinnedMessage.ChannelId = channelId
+ pinnedMessage := &Pins{ChannelId: channelId}
```

2017-12-30 12:56 UTC, kaz commented on model/pins.go
> +  if err != nil {
```diff
- _, err := db.Get("pinnedMessage")
-
- if err != nil {
+ if _, err := db.Get(pinnedMessage); err != nil {
```

2018-01-17 17:06 UTC, tohutohu commented
これブランチ切った頃から大分util系に変更があるのでmasterにリベースするかマージしてほしいです

2018-02-14 02:00 UTC, tohutohu commented
コンフリクトを適切に解消してからプッシュするようにしてください

2018-02-14 05:51 UTC, kaz requested changes
gitの扱いで爆発してそうな辺りを整理しておきました

まだエラーが残ってるっぽいのでcheckしてください
https://circleci.com/gh/traPtitech/traQ/201

`make test`を打つとローカルでテストできるので、
PUSHする前にやっておくと良いと思います

テストのrefactoring(#87)が入ってますが、とりあえず旧来仕様のままmasterに入れてから直しましょう

2018-02-23 12:20 UTC, kaz commented
#123

2018-02-23 12:20 UTC, closed without merging