User認証
traPtitech/traQ pull request #51
Opened 2017-12-25 15:35 UTC by masutech16

絶賛作業中です

2017-12-27 15:11 UTC, tohutohu commented
なんかdevelopブランチout-of-dateだからこれ押してって言われたボタン押したらマージコミット発動して困惑してる

2017-12-27 15:12 UTC, tohutohu commented
SyncSchemaのところがやばばい感じになっているのでいい感じの方法を一緒に考えてほしい

2017-12-27 15:32 UTC, masutech16 reviewed
全体的に目を通しましたが実装は大丈夫だと思いました。

2017-12-27 15:32 UTC, masutech16 commented on model/utils.go
> +
【提案】検証していないんですけどengine.Syncは可変長引数をとれるので、これまとめて投げたらだめですかね
[ref](https://godoc.org/github.com/lunny/xorm#Engine.Sync)

2017-12-27 15:32 UTC, masutech16 commented on router/users.go
> +func PostLogin(c echo.Context) error {
【質問】これらのroutingはAPIではないからswaggerに書かなくてもいいという感じですか？　login処理がどういう位置付けなのかよくわかってないです

2017-12-27 16:55 UTC, tohutohu commented
とりあえず上のあれが終わったらマージするとして、うまくクッキーを使ったテストができませんでした。
具体的には
ログイン前認証必要系で200以外確認
ログイン
認証必要系で200確認ってしたかったんだけど、やりかたわからん！

実際の鯖で動くことはRESTAPI叩く系のツール使って検証しました

2017-12-27 16:55 UTC, tohutohu commented on router/users.go
> +func PostLogin(c echo.Context) error {
書かないといけませんね
書いてコミットします。

2017-12-27 16:59 UTC, tohutohu commented on model/utils.go
> +
よさそうですね
使ってるデータベースの一覧の配列を作りましょう。
DropTableとかもその配列で管理するようにすれば追加したときに楽になりそうですね。
Issue立てました
https://github.com/traPtitech/traQ/issues/53

2017-12-27 17:09 UTC, tohutohu commented on router/users.go
> +func PostLogin(c echo.Context) error {
しました
良ければマージしてください。
あとクライアント側に諸々できるようになった旨を

2017-12-28 05:33 UTC, masutech16 commented
@tohutohu 
単体テストなので、テストとしては間違ったパスワード・ユーザー名でログインできないことと、正しいパスワードでログインできることだけを確認すればよさそうです。
認証前に他のURL叩いてエラーが出る等というのはsessionとそのAPI間のテストなのでここに書く必要はないかなと思います

2017-12-29 17:05 UTC, tohutohu submitted a review, later dismissed

2017-12-30 12:47 UTC, kaz requested changes

2017-12-30 12:47 UTC, kaz commented on router/users.go
> +type loginRequesBoty struct {
typo

2017-12-30 12:47 UTC, kaz commented on router/users.go
> +		return echo.NewHTTPError(http.StatusForbidden, err)
基本的に`err == nil`だと思うので、ログイン失敗時に何も帰ってこなくてちょっと不親切

2017-12-30 12:47 UTC, kaz commented on model/users.go
> +		user.Salt = "popopopopopo"
Salt生成コードを切り出して、ここも乱数生成したsaltを使いましょう

2017-12-30 12:47 UTC, kaz commented on model/users.go
> +	has, err := db.Where("name = ?", user.Name).Get(user)
```diff
- db.Where("name = ?", user.Name).Get(user)
+ db.Get(user)
```

2017-12-30 12:47 UTC, kaz commented on router/users.go
> +	c.Bind(requestBody)
Context.Bindはerrを返すので、適切にHandlingしてください

2017-12-30 12:47 UTC, kaz commented on router/users.go
> +	Pass string `json:"pass"`
jsonじゃなくて、`x-www-form-urlencoded`で受けられるようにすべきです。
Loginは`<form>`で行えたほうが良いので！

2017-12-30 12:49 UTC, kaz commented on router/users.go
> +func PostLogin(c echo.Context) error {
LoginはAPI**ではない**ので、APIdocには載せずに、別途Documentにしてください。

APIを叩くようなクライアントは、別途用意する認証用endpointからTokenを取得します。
OAuthが導入できると良さそう

2017-12-30 12:52 UTC, kaz commented on model/utils.go
> +	developerInsertSQL = "INSERT INTO `users` VALUES ('12b7f9d3-f8af-4690-b72c-8cb58bc6a6f6','masutech16','example@trap.jp','bea362d60712001c3b5892feb738a75f28155e401cf4c69199276507a4d6e9964ef8db6a31987
開発者**個人**のアカウントは入れなくて良いかな……

- `traq:traq`みたいな、インストール後に管理者（使用者）が使うためのアカウントのみをコードに入れましょう。
- 初回用アカウントについては、パスワードがコード中に載っていても良いです。
- Userモデルを使って登録して良いです。

開発中に使う垢については、手で入れるか、register関係の機能ができてから入れましょう。

2017-12-30 12:58 UTC, kaz commented
それと、rebaseしたので、コミットを追加する際は注意してください！！

2017-12-31 07:03 UTC, tohutohu commented on router/users.go
> +		return echo.NewHTTPError(http.StatusForbidden, err)
ログイン失敗時(ok==false)にはerrが必ずnilじゃないようになっています
そのerrの中にエラーメッセージを入れているのですが、違う実装にしたほうが良いでしょうか？

2017-12-31 07:31 UTC, kaz commented on router/users.go
> +		return echo.NewHTTPError(http.StatusForbidden, err)
だったら、そもそもokを返す必要がなさそう
`err != nil`だったらログイン失敗にしておけば良いと思います

ログイン失敗時に何も帰ってこないのは、別の問題っぽい
（エラーハンドラはMessageがstringであることを期待しているが、ログイン失敗時のHTTPErrorはMessageにerror型を持ってる）

2017-12-31 09:19 UTC, kaz submitted a review, later dismissed

2018-01-01 22:25 UTC, merged