ユーザー情報を取得するミドルウェアの実装
traPtitech/traQ pull request #54
Opened 2018-01-02 08:13 UTC by masutech16

#49 を実装しましたが、router側のテストがうまく書けません。
具体的にはsessionを取得するところ(router/middleware_test.go :32)でpanicが発生します。
```
panic: interface conversion: interface is nil, not sessions.Store [recovered]
panic: interface conversion: interface is nil, not sessions.Store
```
ここでセッションが取得できない理由がよく分かりません。見てほしいです

2018-01-03 09:59 UTC, kaz commented
`session.Get()`は内部で`echo.Context`から`sessions.Store`を取り出そうとするんですが、
https://github.com/labstack/echo-contrib/blob/05b673bd85c645d769ea2d10e933f3fa1ee1acfa/session/session.go#L35

`echo.Context`に`sessions.Store`がセットされるのは、実際のリクエスト中にセッション用のmiddlewareが実行されるタイミングです。
https://github.com/labstack/echo-contrib/blob/05b673bd85c645d769ea2d10e933f3fa1ee1acfa/session/session.go#L63

件のmiddlewareは、コ↑コ↓の`mw`がそれです。
https://github.com/traPtitech/traQ/blob/2723454c7ff0704d465530416b053be1a13719c1/router/middleware_test.go#L14

つまるところ、**実際のリクエスト中に`sessions.Store`を取り出してから触る**か、**`sessions.Store`を作成した時に何らかの方法でテスト関数内で利用できるようにする**必要があります。

多分前者のほうがラクで、例えばこんな感じに書くと良いです。
```go
modSessMw := func(next echo.HandlerFunc) echo.HandlerFunc {
	return func(c echo.Context) error {
		sess, err := session.Get("sessions", c)
		if err != nil {
			t.Fatalf("an error occurred while getting session: %v", err)
		}

		sess.Values["userID"] = user.ID
		return sess.Save(c.Request(), c.Response())
	}
}

requestWithContext(t, mw(modSessMw(GetUserInfo(testGetUser))), c)
```

2018-01-03 11:41 UTC, masutech16 commented
無事動きました！　ありがとうございます。
この関数はID以外のユーザー情報を利用するAPIのみに噛ませる感じですかね？
その場合は現状で噛ませる必要のあるrouting関数はなさそうです

2018-01-03 13:46 UTC, kaz requested changes
そうですね、ID以外の情報を使うHandlerはこのGetUserInfoを通さないとテストに通らないですね。
beforeTestが返す`mw`にGetUserInfoをかませたほうが良いのかも？

後ですけど、

- `router.getUserID()`を廃止して、この処理をGetUserInfoに入れる
- `router.getUserID()`でIDを取っていたところを、`Context.Get()`でUser構造体を取り出して、IDを読むようにする
- 各ハンドラに書いてる**ログインしてないユーザを弾く処理**をGetUserInfoに移して共通化

が要りそうです。

2018-01-03 13:46 UTC, kaz commented on router/middleware.go
> +		c.Set("userID", user)
これ、`userID`というか`user`構造体そのものなので、キー名を変えましょう

2018-01-03 13:46 UTC, kaz commented on model/users_test.go
>  	if err != nil {
`if err := ...; err !=nil {`

2018-01-04 05:39 UTC, masutech16 commented
修正しました。
今までテスト時に`testUserID`を毎回生成していたところでユーザーの構造体を生成するようにしました。
Loginのテストだけはmiddlewareをかませると上手くいかないので別の関数にしました。

2018-01-11 06:26 UTC, tohutohu approved these changes

2018-01-13 09:37 UTC, kaz approved these changes

2018-01-13 09:39 UTC, merged