User tag APIの実装
traPtitech/traQ pull request #71
Opened 2018-02-01 16:35 UTC by masutech16

多少DBやAPIのエンドポイントの設計を書き換えた所、すごい変な感じになってしまったので色々と知見がほしいです

2018-02-01 17:02 UTC, tohutohu requested changes
多分スキーマが変わるとまたそこそこ書き換える必要があると思うのでひとまずこれで
ちゃんと確認してなくてすいません
次からはちゃんと確認するようにしましょう

2018-02-01 17:02 UTC, tohutohu commented on docs/db_schema.md
ここのテーブルを2つに分けるってことだった気がします

tagsテーブルに
id,tag,is_locked,created_at,updated_atカラムで
users_tagsテーブルに
user_id,tag_idって感じだったと思います。

2018-02-01 17:02 UTC, tohutohu commented on main.go
> +
apiグループに入れてほしい
starタグも一緒に入れてもらえると嬉しいです

2018-02-02 03:02 UTC, wtks commented on docs/db_schema.md
users_tagsテーブルがユーザーとタグの関係を保持する(関連付けする)テーブルで、
| カラム名 | 型 | 属性 | 説明など | 
| --- | --- | --- | --- |
| user_id | CHAR(36) | PRIMARY KEY | ユーザーID |
| tag_id | CHAR(36) | NOT NULL | タグID |
| is_locked | BOOLEAN | NOT NULL | ロックされているか |
| created_at | TIMESTAMP | NOT NULL | 作成日時 |
| updated_at | TIMESTAMP | NOT NULL | 更新日時 |
user_idとtag_idは複合ユニーク制約

tagsテーブルは全てのタグをid管理するテーブルで、
| カラム名 | 型 | 属性 | 説明など | 
| --- | --- | --- | --- |
| id | CHAR(36) | PRIMARY KEY | タグID |
| name | VARCHAR(30) | NOT NULL, UNIQUE | タグ文字列 |

な感じですかね。普通のテーブル設計ではtagsテーブルのnameにユニーク制約をつけて、同一名のタグを入れないようにすべきですけど、そうするとnameの型はtextだと無理なのでvarcharにしないといけなくなって、結局タグの字数制限がつきますね・・・。タグ名をハッシュしてname_hashみたいなカラムを追加してそれにユニーク制約つけるとtext型のままでもいけるけどそこまでする必要無い気がする。
そうすると、テーブル分ける意義が無くなるかもしれないけど、今後特殊なタグ(管理人でないと追加、削除できないようなタグ、学年とか所属など？)を実装するなら分けといたほうがいい。

is_lockedはユーザー別でそのタグをロックするかを決めるのでusers_tagsテーブルのほうにあるべきです。(created_at,updated_atも同様)
updated_atはユーザーがタグをロック、アンロックした時しか更新されない気がするのでなくてもいいかもしれません。

上の設計で行くとデーターベースの操作としては、
ユーザーがタグを追加した場合は、まずそのタグがtagsになければ挿入。それからそのタグIDとユーザーIDの対をusers_tagsテーブルに挿入。
タグを削除した場合は、users_tagsテーブルからそのユーザーとタグのIDの対を削除。tagsテーブルにはなにもしない。

2018-02-07 02:06 UTC, masutech16 commented
現在↑のを参考に編集しています。
また、APIの設計で一つ相談したいことがあります。
今はDELETE以外のメソッドが叩かれたときに変更後のリストを返しています。個人的にはPOST・PUTの場合は必要ないような気もする(GET)以外は返さなくてよいと思うのですが、意見が欲しいです。

2018-02-11 11:18 UTC, tohutohu commented on model/users.go
>  }
これIDが空じゃないかとか見なくても大丈夫ですか

2018-02-11 12:33 UTC, masutech16 commented on model/users.go
>  }
IDが入ってるならそれはもう存在するで確定なはずなので、名前が入っているかどうかだけを確認する用にしました

2018-02-11 12:33 UTC, tohutohu approved these changes

2018-02-11 15:14 UTC, merged