[WIP]Add Stamp palettes
traPtitech/traQ pull request #814
Opened 2020-03-18 07:42 UTC by ryoha000

Close #450

2020-03-18 10:38 UTC, wtks requested changes

2020-03-18 10:38 UTC, wtks commented on model/stamp_palettes.go
> +	UpdatedAt   *time.Time `gorm:"precision:6"`
ポインタじゃなくて値にしてください

2020-03-18 10:38 UTC, wtks commented on model/stamp_palettes.go
> +	Description string    `gorm:"type:varchar(1000)"`
text型にしてnot nullつけてもらえますか

2020-03-18 10:38 UTC, wtks commented on model/stamp_palettes.go
> +	Stamps      []Stamp
これだとカラムとして扱われないので直す必要があるんですが、今回の場合はこのスタンプの配列の順番を保持したままDBに保存しないといけないのと、配列の特定の要素１つずつを取り出す必要があるユースケースは考えられないので、正規化せず、テーブルのカラムとしては`stamps`という名前の`text (not null)`型にして、「スタンプのUUIDの配列」の文字列を格納するようにしましょう。

Go側では、新たに`type UUIDs []uuid.UUID`という型を定義して、その型に対して`database/sql/driver.Valuer`と`database/sql.Scanner`インターフェイスを実装して、StampPalette構造体のフィールドとしては`Stamps UUIDs`にしてください。

具体的にはhttps://github.com/traPtitech/traQ/blob/63f25534fe09f5c99673791188f54712539b0839/model/oauth2.go#L26 こういう風に型を作って、https://github.com/traPtitech/traQ/blob/63f25534fe09f5c99673791188f54712539b0839/model/oauth2.go#L29 https://github.com/traPtitech/traQ/blob/63f25534fe09f5c99673791188f54712539b0839/model/oauth2.go#L34 風にインターフェイスを実装して、https://github.com/traPtitech/traQ/blob/63f25534fe09f5c99673791188f54712539b0839/model/oauth2.go#L122 風に使ってください。ただし、この例だと配列じゃなくてmapなので注意

こんな感じでValuer・Scannerインターフェイスを実装すると、テーブルからデータを出し入れするときに自動的に型を変換してくれます。(今回の場合だと、書き込み時はUUIDの配列→文字列、読み込み時はその逆)

2020-03-18 12:10 UTC, ryoha000 commented
[ここ](https://godoc.org/github.com/gofrs/uuid#FromString)をみて実装しましたがScanのあたりが特に自信がないです

2020-03-18 12:53 UTC, wtks commented on model/stamp_palettes.go
> +	Description string    `gorm:"type:text(1000);not null"`
あ、text型は文字数指定要らないです

2020-03-18 12:53 UTC, wtks commented on model/stamp_palettes.go
> +		return errors.New("failed to scan Stamps")
uuid.FromStringの戻り値のerrがnilの場合のみappendするようにしておいてもらえますかね。errがnilでない場合は無視してcontinueでいいです。

あと、UUIDsはstampID配列に限らず使えそうなので、変数名とエラーメッセージをstampを含まないような表現にしてほしいです。

2020-03-18 15:11 UTC, wtks reviewed
じゃあ次に、既にあるデータベースに今回定義したテーブルを作成するためのマイグレーション用コードをmigrationパッケージ以下に書いてください。

migrationパッケージの説明→ https://godoc.org/github.com/traPtitech/traQ/migration

具体的にはこんな感じ→ https://github.com/traPtitech/traQ/blob/63f25534fe09f5c99673791188f54712539b0839/migration/v3.go#L15
今回は既存のテーブルは変更しないので、AutoMigrateすればテーブル作成してくれます。

マイグレーションのIDなんですけど、クリップの方で`11`を使うので`12`にしてください。

2020-03-18 23:57 UTC, wtks commented on migration/v12.go
> +			return nil
https://github.com/traPtitech/traQ/blob/63f25534fe09f5c99673791188f54712539b0839/migration/v3.go#L19
の様にCreatorIDにusersテーブルのidへ外部キー制約をつけてもらえますか

2020-03-18 23:57 UTC, wtks commented on .tbls.yml
> +  - table: stamp_palettes
`make db-gen-docs`を実行して、docs/dbschema以下のドキュメントを更新してほしいです

2020-03-18 23:57 UTC, wtks commented on migration/current.go
> +		&model.StampPalette{},
テストコードとかでテーブルをドロップする処理があって、この配列の順番でテーブルが削除されるんですけど、外部キー制約の関係上Userよりも前にStampPaletteを削除する必要があるので、model.Userより上にしてほしいです。

2020-03-19 00:21 UTC, wtks commented on migration/v12.go
> +			return nil
外部キー制約をつけたら、current.goの方にも追加するのを忘れずに

2020-03-22 08:11 UTC, wtks commented
ごめんできてる事に気づいてなかった
APIハンドラの方を実装していきましょう。
https://github.com/traPtitech/traQ/pull/815#pullrequestreview-377319072

2020-03-22 17:25 UTC, ryoha000 reviewed
寝るのでWIPですがあげます
？ってなったところはレビューのコメントに書きました
`/router/v1/router_test.go`で`cannot use repo (variable of type *TestRepository) as repository.Repository value in argument to rbac.New: missing method CreateStampPalette`みたいなエラーが6つ出ましたが現在分からずです
明日考えます

2020-03-22 17:25 UTC, ryoha000 commented on repository/stamp_palette_impl.go
> +		}
ここどうでしょうか

2020-03-22 17:25 UTC, ryoha000 commented on repository/stamp_palette_impl.go
> +	})
ここ以外もですがevent周りがよくわかりませんでした

2020-03-22 17:25 UTC, ryoha000 commented on repository/stamp_palette.go
> +	// model.UUIDsにnullかどうかを持たせるか悩んでます
コメントの通りです

2020-03-23 00:19 UTC, wtks commented on repository/stamp_palette.go
> +	// model.UUIDsにnullかどうかを持たせるか悩んでます
Descriptionのみ変更する場合などが考えられるので、nullかどうかを持たせてほしいですが、`model.UUIDs`はスライス`[]uuid.UUID`の別名で、Goはスライスはポインタ型という仕様なので、これはもう既にnullableなのでそのままで大丈夫です。(スライス`s`のnil (`s == nil`)・空配列 (`s != nil && len(s) == 0`)・1つ以上の要素を含む配列 (`len(s) > 0`)は区別できます)

2020-03-23 00:19 UTC, wtks commented on router/v3/utils.go
> +// getParamStampPalette URLの:stampIDに対応するStampを取得
忘れないうちにコメントしておきますが、コメントの方を修正してください

2020-03-23 00:19 UTC, wtks commented on router/v3/stamp_palettes.go
> +			return herror.BadRequest(err)
`userID (getRequestUserID(c))`が`nil`になることは無いので、これは必要なくても大丈夫です。

2020-03-23 00:19 UTC, wtks commented on repository/stamp_palette_impl.go
> +	})
これで良いです。traQではプロセス内部でPub/Subベースのメッセージング(イベント処理)を採用してて、repo.hub.Publishを呼び出すことで、イベントハブにイベントを発行します。で、発行したイベントは予めhub.Subscribeしておいた関数に届いて実行されます。

`event.StampCreated`になっているので、stamppaletteの方に直しておいてください。

2020-03-23 00:19 UTC, wtks commented on repository/stamp_palette_impl.go
> +		}
あースタンプの存在チェックのこと忘れてました。
`SELECT count(*) FROM stamps WHERE id IN (?)`に相当するクエリのように、`IN`句でstampsの中身を一気に条件に指定して、引っかかったものの数がstampsの配列の長さと一致するかどうかで確認するのはどうですか

2020-03-23 00:22 UTC, wtks commented
構造体がインターフェイスを実装できてないというエラーです。
`router/v1/router_repository_test.go`で`TestRepository`構造体が`repository.Repository`を実装してないとテストは動きません。v1ではStampPaletteは使わないので、とりあえず`TestRespository`構造体に対して、`StampPaletteRepository`の関数を中身`panic("implement me")`にして
全て実装してください。

2020-03-23 06:02 UTC, ryoha000 commented on repository/stamp_palette.go
> +	ExistStamps(stampIDs model.UUIDs) (err error)
これは`repository/stamp.go`に置いてる方がいいでしょうか？

2020-03-23 06:02 UTC, ryoha000 commented on utils/validator/rules.go
> +}
コメントの通りです

2020-03-23 06:02 UTC, ryoha000 commented on repository/stamp_palette_impl.go
> +		}
ozzo-validationは全然わからないですが引数のstampsにnilをいれられないのはテストのときスタンプを作ってめんどくさいのかなって思いました

2020-03-23 06:03 UTC, wtks commented on repository/stamp_palette.go
> +	ExistStamps(stampIDs model.UUIDs) (err error)
それがいいですね

2020-03-23 06:07 UTC, wtks commented on repository/stamp_palette_impl.go
> +		}
APIの仕様的にはスタンプが何も登録されていないスタンプパレットを作成することを許容してるので、そういうときは`nil`ではなく、`model.UUIDs{}`で空の配列を引数で渡せばいいと思います

2020-03-23 06:09 UTC, wtks commented on utils/validator/rules.go
> +}
APIの仕様的にはスタンプが何も登録されていないスタンプパレットを作成することを許容してるので0でいいです

2020-03-23 06:13 UTC, wtks commented on router/v3/stamp_palettes.go
> +	if user.GetID() != stampPalette.CreatorID && !h.RBAC.IsGranted(user.GetRole(), permission.EditStampPalette) {
`!h.RBAC.IsGranted(user.GetRole(), permission.EditStampPalette)`は、https://github.com/traPtitech/traQ/blob/d8d7c720d99bcede56c8f966f9c67454053eaa27/router/v3/router.go#L202 のrequiresで既にチェック入ってるので、userのIDのチェックだけで大丈夫です。DeleteStampPaletteも同様

2020-03-23 06:14 UTC, wtks commented on repository/stamp_palette_impl_test.go
> +	stampIDs := make([]uuid.UUID, 10)
```suggestion
	stampIDs := make([]uuid.UUID, 0, 10)
```

2020-03-23 06:21 UTC, wtks commented on utils/validator/rules.go
> +	vd.Required,
https://github.com/traPtitech/traQ/pull/814#discussion_r396227613 と関係してるけど、確かvd.Requiredだとnilも空配列も弾く気がするので、vd.NotNilでnilだけ弾くようにしたほうがいいかも

2020-03-23 14:42 UTC, wtks commented on repository/stamp_palette_impl.go
> +		if err = validation.Validate(description, validator.StampPaletteDescriptionRuleRequired...); err != nil {
これRequiredだと0文字descriptionが弾かれると思う

2020-03-23 14:46 UTC, wtks commented on repository/stamp_palette_impl.go
> +		if err = validation.Validate(description, validator.StampPaletteDescriptionRuleRequired...); err != nil {
UpdateStampPaletteの方も同様

2020-03-23 14:50 UTC, ryoha000 commented on repository/stamp_palette_impl_test.go
> -			assert.Equal(stamps, sp.Stamps)
ここだけじゃないですが型がめんどくさくてstampsの比較を消しました
他のNameとかの比較でテストはいいかなと思うのですが比較あった方がいいですか？

2020-03-23 14:51 UTC, ryoha000 commented on repository/stamp_palette_impl.go
> +		if err = validation.Validate(description, validator.StampPaletteDescriptionRuleRequired...); err != nil {
0文字を許容するならruleをRequired→NotNilにした方がいいですか？

2020-03-23 14:54 UTC, wtks commented on repository/stamp_palette_impl_test.go
> -			assert.Equal(stamps, sp.Stamps)
`stamps := make([]uuid.UUID, 0)`じゃなくて`stamps := model.UUIDs{}`にするか、`assert.Equal`じゃなくて`assert.EqualValues`にすれば通ると思う

2020-03-23 14:59 UTC, wtks commented on repository/stamp_palette_impl.go
> +		if err = validation.Validate(description, validator.StampPaletteDescriptionRuleRequired...); err != nil {
このdescriptionはstring型でnilは入らないから単にRequiredとって`validator.StampPaletteDescriptionRule`にすればいいんじゃないかな

2020-03-23 15:03 UTC, wtks commented on repository/stamp_palette_impl.go
> +	return sps, tx.Find(&sps).Error
これ`userID`を使わずに、全スタンプパレットを返してしまってます

2020-03-23 21:46 UTC, ryoha000 commented
手元だと
```
(/mnt/e/Users/ryoha/Documents/workspace/traQ/repository/user_impl.go:41)
[2020-03-24 06:33:00]  Error 1062: Duplicate entry 'dTDTdI1G2E' for key 'name'

(/mnt/e/Users/ryoha/Documents/workspace/traQ/repository/tag_impl.go:77)
[2020-03-24 06:33:04]  Error 1062: Duplicate entry '5156a90e-d655-4364-8926-5865d067ea6c-84d14e68-cf9b-4052-b799-5e1' for key 'PRIMARY'

(/mnt/e/Users/ryoha/Documents/workspace/traQ/repository/user_group_impl.go:32)
[2020-03-24 06:33:13]  Error 1062: Duplicate entry 'm7pdWijIU79p3hoHU7VC' for key 'name'

(/mnt/e/Users/ryoha/Documents/workspace/traQ/repository/message_impl.go:43)
[2020-03-24 06:33:14]  Error 1213: Deadlock found when trying to get lock; try restarting transaction
--- FAIL: TestRepositoryImpl_CreateMessage (1.04s)
    --- FAIL: TestRepositoryImpl_CreateMessage/success_1 (0.06s)
        message_impl_test.go:33:
                Error Trace:    message_impl_test.go:33
                Error:          Received unexpected error:
                                Error 1213: Deadlock found when trying to get lock; try restarting transaction
                Test:           TestRepositoryImpl_CreateMessage/success_1

(/mnt/e/Users/ryoha/Documents/workspace/traQ/repository/channel_impl.go:637)
[2020-03-24 06:33:15]  Error 1452: Cannot add or update a child row: a foreign key constraint fails (`traq-test-repo-common`.`users_subscribe_channels`, CONSTRAINT `users_subscribe_channels_user_id_users_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE)
FAIL
FAIL    github.com/traPtitech/traQ/repository   70.958s
```
みたいなエラーがそれなりの頻度で出ますがよくわからずになってます

2020-03-23 23:33 UTC, wtks reviewed
あーそれは、#585 ですね。テストを並列化して、DBへの書き込みが同時に行われるせいでデッドロックが起こる場合があります。テストしたいテスト関数だけテストを実行するか、デッドロックで落ちた既存のテストは無視するか、テストガチャしてください・・・

なんかいい感じの対策が思いつかないので放置してます。テストを直列にすれば発生しなくなるはずですが、テスト時間が更に長くなると思われる。

2020-03-23 23:33 UTC, wtks commented on notification/handlers.go
> +	broadcast(ns, &sse.EventData{
全ユーザーにbroadcastじゃなくて、スタンプパレットの作成者に対してuserMulticastでお願いします。

2020-03-23 23:33 UTC, wtks commented on notification/handlers.go
> +	broadcast(ns, &sse.EventData{
後swagger(`v3-api.yaml`)の`/ws`のgetの`description`に、追加したイベントに関する説明を追記しといてください

2020-03-23 23:33 UTC, wtks commented on router/v3/stamp_palettes.go
> +		vd.Field(&r.Name, validator.StampPaletteNameRule...),
こっちの方は`StampPaletteNameRuleRequired`で

2020-03-23 23:39 UTC, wtks commented on notification/handlers.go
> +	broadcast(ns, &sse.EventData{
上2つとも他のスタンプパレットイベントも同様に。

2020-03-24 00:19 UTC, wtks commented on notification/handlers.go
> +	broadcast(ns, &sse.EventData{
ちなみに僕はswaggerのファイル編集はStoplight Studioっていうアプリを使ってやってます

2020-03-24 07:17 UTC, ryoha000 commented on repository/stamp_palette_impl.go
> +	stampPalette, err := repo.GetStampPalette(id)
最初useIDを関数の引数に取らせようと思いましたが、管理者が削除するときの挙動が少しめんどくさそうだったので1回とってくるようにしました
Deleteはあまり叩かれないと思うのでクエリ数が1増えてもいいかなと思うのですがどうでしょうか？

2020-03-24 07:23 UTC, wtks commented on repository/stamp_palette_impl.go
> +	stampPalette, err := repo.GetStampPalette(id)
一回取ってくる方で実装を想定してたのでそれでいいです

2020-03-24 07:30 UTC, wtks commented on repository/stamp_palette.go
> +	// DeleteStamp 指定したIDのスタンプパレットを削除します
```suggestion
	// DeleteStampPalette 指定したIDのスタンプパレットを削除します
```

2020-03-24 07:30 UTC, wtks commented on repository/stamp_palette_impl.go
> +// GetAllStamps implements StampPaletteRepository interface.
```suggestion
// GetStampPalettes implements StampPaletteRepository interface.
```

2020-03-24 07:31 UTC, wtks commented
出来てそうなので、コミットしたgoファイルにgofmtかけといてください

2020-03-24 07:48 UTC, wtks submitted a review, later dismissed

2020-03-25 02:51 UTC, wtks commented
clipがマージされたらマージします。多分コンフリクト発生するので、クリップマージされたらマスターにリベースしてください。

2020-03-25 05:38 UTC, Hosshii commented on repository/repository_test.go
> +func mustMakeStampPalette(t *testing.T, repo Repository, name, discription string, stamps []uuid.UUID, userID uuid.UUID) *model.StampPalette {
descriptionなきがする

2020-03-25 06:03 UTC, wtks commented
docs/dbschemaはコンフリクト解決しなくていいので、再生成してください

2020-03-25 07:24 UTC, ryoha000 commented
pull rebaseしちゃったのでもう一回approveしてほしいです:pray:

2020-03-25 13:30 UTC, wtks approved these changes

2020-03-25 13:30 UTC, merged