WIP : add Clip
traPtitech/traQ pull request #815
Opened 2020-03-18 07:55 UTC by Hosshii

2020-03-18 10:01 UTC, wtks requested changes

2020-03-18 10:01 UTC, wtks commented on model/clip.go
> +	FolderID    uuid.UUID `gorm:"type:char(36);not null;index"`
冗長なので単に`ID`でいいです。あと`OwnerID`がindexで、こっちがprimary keyですね。

2020-03-18 10:01 UTC, wtks commented on model/clip.go
> +	Description string    `gorm:"type:varchar(1000)"`
typeの`varchar(1000)`はmysqlの仕様上作れないので、text型にしてnot nullをつけてください。

2020-03-18 10:01 UTC, wtks commented on model/clip.go
> +	return "clip_folder"
```suggestion
	return "clip_folders"
```

2020-03-18 10:01 UTC, wtks commented on model/clip.go
> +	MessageID uuid.UUID `gorm:"type:char(36);not null;"`
`FolderID`と`MessageID`のどっちもprimary keyにしてください

2020-03-18 10:03 UTC, wtks commented on model/clip.go
> +	Description string    `gorm:"type:varchar(1000)"`
仕様上作れないってのは嘘です。でもtext型にしといてください

2020-03-18 10:56 UTC, wtks commented on model/clip.go
> +	MessageID uuid.UUID `gorm:"type:char(36);not null;"`
↑すると、FolderIDとMessageIDの複合プライマリキーが作られて、テーブル上ではタプルがFolderIDとMessageIDの組に対して一意になります

2020-03-18 12:54 UTC, Hosshii commented
修正できたと思います

2020-03-18 13:12 UTC, wtks reviewed
これが修正できたら、既にあるデータベースに今回定義したテーブルを作成するためのマイグレーション用コードをmigrationパッケージ以下に書いてください。

migrationパッケージの説明→ https://godoc.org/github.com/traPtitech/traQ/migration

具体的にはこんな感じ→ https://github.com/traPtitech/traQ/blob/63f25534fe09f5c99673791188f54712539b0839/migration/v3.go#L15
今回は既存のテーブルは変更しないので、AutoMigrateすればテーブル作成してくれます。

2020-03-18 13:12 UTC, wtks commented on model/clip.go
> +	Description string    `gorm:"type:text"`
not nullもつけといてください

2020-03-18 13:12 UTC, wtks commented on model/clip.go
> +// ClipFolders クリップフォルダーの構造体
コメントの方も単数に修正お願いします

2020-03-18 15:25 UTC, wtks reviewed
良さそうなので、`docker-compose up -d --build`を実行し直してみて、鯖起動後にデータベースにちゃんとテーブルが追加されているかどうか確認してみてください。

問題なかったら、https://github.com/traPtitech/traQ/tree/master/docs/dbschema 以下の自動生成のドキュメントを更新したいので、https://github.com/traPtitech/traQ#generate-db-schema-docs を行ってください。

2020-03-18 15:30 UTC, wtks reviewed
ドキュメントが正しく更新されてない場合は、 https://github.com/traPtitech/traQ/runs/516811382 のLintが落ちます。db-gen-docsするには、https://github.com/traPtitech/traQ/blob/master/.tbls.yml に新しく追加したテーブルのカラムの説明も書く必要があります。

2020-03-18 15:33 UTC, Hosshii commented
了解しました。やってみます

2020-03-18 16:36 UTC, Hosshii commented
`tbls`インストールして`make up-test-db`をしたあとに`make db-gen-docs`をしたら、ほかのdocも書き変わってしまったのですがそれでも大丈夫でしょうか

2020-03-19 00:17 UTC, wtks reviewed
問題ないので変更されたドキュメント全てをコミットしてください。

じゃあAPIを実装し始めましょう。基本的にrouter/v3パッケージ以下に各APIのハンドラを既に実装されてるハンドラを参考にしながら実装して、https://github.com/traPtitech/traQ/blob/63f25534fe09f5c99673791188f54712539b0839/router/v3/router.go#L293 にハンドラを登録してください。
https://github.com/traPtitech/traQ/blob/63f25534fe09f5c99673791188f54712539b0839/router/v3/router.go#L144 では、`"/messages/:messageID"`のグループに`retrieve.MessageID()`と`requiresMessageAccessPerm`ミドルウェアがついてて、そのグループ以下のAPIで必要なメッセージの存在確認・DBからの取得や、アクセス権限の確認といった共通処理がミドルウェア化されてる(https://github.com/traPtitech/traQ/blob/63f25534fe09f5c99673791188f54712539b0839/router/middlewares/param_retriever.go#L90 https://github.com/traPtitech/traQ/blob/63f25534fe09f5c99673791188f54712539b0839/router/middlewares/access_control.go#L154 )ので、同じ感じで`"/:folderID"`グループにミドルウェアを実装するといいと思います。

で、APIのハンドラが必要なDBからのデータ取得・書き込み処理を、repositoryパッケージ以下に`ClipRepository`インターフェースを定義して、それを`GormRepository`構造体に対して実装してください。（例：インターフェース https://github.com/traPtitech/traQ/blob/master/repository/user.go 実装 https://github.com/traPtitech/traQ/blob/master/repository/user_impl.go)

2020-03-19 00:17 UTC, wtks commented on migration/current.go
> +		&model.ClipFolderMessage{},
テストコードとかでテーブルをドロップする処理があって、この配列の順番でテーブルが削除されるんですけど、外部キー制約の関係上ClipFolderよりも前にClipFolderMessage、Userよりも前にClipFolder、Messageよりも前にClipFolderMessageを削除する必要があるので、それを満たす様な箇所に書き換えてほしいです。

2020-03-22 06:48 UTC, Hosshii commented
https://traptitech.github.io/traQ/?urls.primaryName=v3%20API#/clip/getClips
ここで`x-traq-more-clipfoldermessage`みたいなヘッダーっていりませんか？

2020-03-22 07:08 UTC, wtks commented
あーそうですね。メッセージ取得系APIと同じ様に`x-traq-more`追加しといてください。

2020-03-22 07:12 UTC, wtks commented
ちなみに僕はswaggerのファイルはStoplight Studioっていうアプリを使ってやってます

2020-03-22 07:38 UTC, Hosshii commented
把握しました
ありがとうございます

2020-03-22 07:48 UTC, wtks commented on repository/clip_impl.go
> +}
このままだとクリップフォルダ内のメッセージではなくて、全メッセージの中からにlimit件取得することになるので、`clip_folder_messages`テーブルを内部結合する必要があります。

2020-03-22 07:48 UTC, wtks commented on router/middlewares/access_control.go
> +			}
グループの所属はクリップフォルダのアクセス権に関係無いので削除してください

2020-03-22 07:48 UTC, wtks commented on router/v3/responses.go
> +	FolderID uuid.UUID
この`FolderID`なんですけど、レスポンスの全メッセージに対して全部同じIDになって冗長なことに気づいたので削除しておいてもらえますか。swaggerの方もけしておいてください。

2020-03-22 07:50 UTC, wtks commented on router/v3/responses.go
> +	FolderID uuid.UUID
`#/components/schemas/ClippedMessage`の話です

2020-03-22 12:45 UTC, wtks commented on repository/clip_impl.go
> +func (repo *GormRepository) GetClipFolderMessages(folderID uuid.UUID, query ClipFolderMessageQuery) (messages []*ClipFolderMessage, more bool, err error) {
ごめん、INNER JOINが必要って言ったんですが、それだと実装が複雑になることに気づきました。`ClippedAt`を返す必要がある事を忘れてました。

新しく定義した`repository.ClipFolderMessage`と`repository.Message`構造体を使うのではなく、`[]*model.ClipFolderMessage `を返すようにしてもらえませんか。というのは、repositoryが返すメッセージに関する型は統一したいっていうのと、messagesテーブルからはピンされているかどうかのフラグ・スタンプのリストは得られないので別で取得する必要があり、既に実装されている関数ではそれをgormのPreloading機能を使って実装しています。例えば、今回実装するものと似たような処理である、指定したチャンネルのピンメッセージの配列を返す処理では、https://github.com/traPtitech/traQ/blob/4ef16c916a7fb4d0a5b85699650025bcfc27f0e5/repository/pin_impl.go#L122 https://github.com/traPtitech/traQ/blob/4ef16c916a7fb4d0a5b85699650025bcfc27f0e5/repository/pin_impl.go#L129 
https://github.com/traPtitech/traQ/blob/4ef16c916a7fb4d0a5b85699650025bcfc27f0e5/model/pins.go#L12 のように実装してます。
なので、`model.ClipFolderMessage`構造体にhttps://github.com/traPtitech/traQ/blob/4ef16c916a7fb4d0a5b85699650025bcfc27f0e5/model/pins.go#L12 の`Message`フィールドと同じものを追加して、Preloadingを使って実装にしてください。

2020-03-22 12:51 UTC, wtks commented on repository/clip_impl.go
> +func (repo *GormRepository) GetClipFolderMessages(folderID uuid.UUID, query ClipFolderMessageQuery) (messages []*ClipFolderMessage, more bool, err error) {
ただし、pinPreloadsでは`Message.Pin`をPreloadしてないので、それを追加する必要があるのと、今回のクリップメッセージの場合は、https://github.com/traPtitech/traQ/blob/4ef16c916a7fb4d0a5b85699650025bcfc27f0e5/repository/pin_impl.go#L123 のようなJOINは必要ないはずです。
また、limitとかoffsetとかに関しては、https://github.com/traPtitech/traQ/pull/815/files#diff-71282458ec5d8dafa718d1b6ab24f703R152-R170 と同じでいけると思います

2020-03-22 14:08 UTC, ryoha000 commented on router/v3/responses.go
> +		Name:        cf.Description,
ここnameもDescriptionからとってるよ

2020-03-23 09:48 UTC, Hosshii commented on repository/clip_impl.go
> +func (repo *GormRepository) GetClipFolderMessages(folderID uuid.UUID, query ClipFolderMessageQuery) (messages []*ClipFolderMessage, more bool, err error) {
修正できたと思います

2020-03-23 13:16 UTC, wtks commented on utils/validator/rules.go
> +	vd.Match(regexp.MustCompile(`^[a-zA-Z0-9_]+$`)).Error("must contain [a-zA-Z0-9_] only"),
フォルダ名に使える文字の制約は無いです

2020-03-23 13:16 UTC, wtks commented on repository/clip.go
> +	UpdateClipFolder(folderID uuid.UUID, name string, description string) error
このままだと`name`と`description`の片方だけ変更したい時にどちらも指定しないといけない(変更しない方は現状の値を与える必要が出てしまう)ので、`string`ではなく`null.String`を使うといいです

2020-03-23 13:20 UTC, wtks commented on repository/clip.go
> +	Order  string `query:"order"`
これ2値なので、`Desc bool`にしてもらえますか

2020-03-23 13:28 UTC, wtks commented on router/v3/clips.go
> +	cfm, err = h.Repo.AddClipFolderMessage(cf.ID, req.MessageID)
GetMessageでメッセージが存在しなかった(ErrNotFound)場合は、400エラー("invalid messageId")を返すようにしてください。
加えて、メッセージが存在した場合は https://github.com/traPtitech/traQ/blob/master/router/middlewares/access_control.go#L161 のように、そのメッセージにリクエストしてきたユーザーがアクセス出来るかどうかをチェックして、アクセス不可だった場合は400エラー("invalid messageId")を返すようにしてください。

2020-03-23 13:31 UTC, wtks commented on router/v3/clips.go
> +		return herror.InternalServerError(err)
既にクリップされていた場合は409エラーを返してください

2020-03-23 15:19 UTC, wtks commented on repository/clip_impl.go
> +		return tx.Create(cfm).Error
これ必ずエラーになってます

2020-03-23 15:28 UTC, wtks commented on router/v3/clips.go
> +		return herror.InternalServerError(err)
Repo.DeleteClipFolderMessageは、既に存在していない場合ErrNotFoundを返すようになってますが、APIの仕様では既にフォルダ内に存在していないメッセージが指定された場合はエラーを返さず、204を返すことになっているので、そうなるようにしてください。

それと、`retrieve.MessageID()`でメッセージ本体取ってくる必要は無いかな。DeleteClipFolderのハンドラと同じように、getParamAsUUIDでmessageIDだけ取ってくればいいと思う。メッセージのアクセス権限チェックも要らないです

2020-03-23 15:41 UTC, wtks commented on router/v3/clips.go
> +		return err
InternalServerErrorですね

2020-03-23 15:41 UTC, wtks commented on router/v3/clips.go
> +		return herror.InternalServerError(err)
これだと、引数のバリデーション失敗が400じゃなくて500で返ってしまうので、PostClipFolderRequestにValidate() errorメソッド実装して、bindAndValidate呼び出し部分でバリデーションするようにするか、ここのerrを分岐させて400を返してください。EditClipFolderのハンドラも同様

2020-03-23 15:44 UTC, wtks commented
後テストが落ちてしまっているので、これ( https://github.com/traPtitech/traQ/pull/814#issuecomment-602304895 )と同様のことをClipRepositoryに読み替えてしてください

2020-03-23 17:18 UTC, Hosshii commented on repository/clip_impl.go
> +		return tx.Create(cfm).Error
ここってフォルダが存在するかどうかもdbExitsでとる感じでいいでしょうか

2020-03-23 17:31 UTC, Hosshii commented on router/v3/clips.go
> +		return herror.InternalServerError(err)
requires(permission.GetMessage)がいらないってことでしょうか

2020-03-23 18:26 UTC, Hosshii commented on router/v3/clips.go
> +		return herror.InternalServerError(err)
PostClipFolderRequestとUpdateClipFolderRequestにValidate() errorメソッド実装しました

2020-03-23 18:29 UTC, Hosshii commented
clipfolderを削除してもclipfoldermessageが削除されない気がするのであとで修正します

2020-03-24 00:06 UTC, wtks reviewed
一応外部キー制約をON DELETE CASCADEで貼ってるので、フォルダがテーブルから消えれば、それを参照しているクリップフォルダメッセージは勝手に全て消えると思いますが、削除処理を明示的書いた方がわかりやすいですね。

同様に、メッセージが削除された時にそれを参照しているクリップフォルダメッセージが削除されるように、 https://github.com/traPtitech/traQ/blob/2786b98733f06e758053e42845cee67f98c16817/repository/message_impl.go#L132 にDeleteを追加しておいてください

2020-03-24 00:06 UTC, wtks commented on notification/handlers.go
> +	broadcast(ns, &sse.EventData{
全ユーザーにbroadcastじゃなくて、クリップフォルダの所有者に対してuserMulticastでお願いします。他のクリップフォルダのイベントも同様に。

2020-03-24 00:06 UTC, wtks commented on notification/handlers.go
> +			"clip_folder_message_id": ev.Fields["clip_folder_message_id"].(uuid.UUID),
単に`message_id`でいいと思います。

2020-03-24 00:06 UTC, wtks commented on notification/handlers.go
> +	broadcast(ns, &sse.EventData{
後swagger(`v3-api.yaml`)の`/ws`のgetの`description`に、追加したイベントに関する説明を追記しといてください

2020-03-24 00:06 UTC, wtks commented on router/v3/clips.go
> +		return herror.InternalServerError(err)
？
`requires(permission.GetMessage)`はそもそもついてないと思いますが。
一応ここで言ってるのは、`DELETE /clip-folders/:folderID/messages/:messageID`のみに限った話です。

2020-03-24 00:06 UTC, wtks commented on router/v3/clips.go
> +	Limit  int    `query:"limit"`
repositoryのGetClipFolderMessages関数のlimitは無制限のままにして、ユーザーに公開するAPIハンドラ側ではLimitを、最小1、最大200、デフォルト値20に制限してください。

デフォルト値は、ユーザーがAPIのリクエストにlimitを指定しなかった場合ここの値が0になると思うので、その時20に書き換えればいいです。

2020-03-24 00:12 UTC, wtks commented on repository/clip_impl.go
> +		return tx.Create(cfm).Error
イベントのハンドラの修正の際に、フォルダが存在するかどうかをdb.Firstで取ることが必要になると思います。

2020-03-24 10:00 UTC, Hosshii commented on repository/clip_impl.go
> +		return tx.Create(cfm).Error
db.Firstでフォルダ確認するようにしました

2020-03-24 10:26 UTC, Hosshii commented
クリップフォルダーメッセージをpostすると502が帰ってくるときと、正常に帰ってくる時があって、両方ともdbにはデータが追加されてる、みたいになって

2020-03-24 10:36 UTC, wtks commented on repository/clip.go
> +	// DeleteClipFolder 指定したクリップフォルダーメッセージを削除します。
```suggestion
	// DeleteClipFolderMessage 指定したクリップフォルダーメッセージを削除します。
```

2020-03-24 10:39 UTC, wtks commented on repository/clip_impl.go
> +			"clip_folder_message":     &cfm,
ここタイポしてますね。あと`&cfm`はポインタのポインタになってるので`cfm`でいいです

2020-03-24 13:08 UTC, wtks commented on event/topic.go
> +	ClipFolderMessageAdded   = "clip_folder_message.added"
コメント追加しといてください

2020-03-24 13:13 UTC, wtks commented on router/v3/responses.go
> +	Message   *Message  `json:message`
```suggestion
	Message   *Message  `json:"message"`
```

2020-03-24 13:24 UTC, wtks commented on router/v3/clips.go
> +// PostClipFolders POST /clip-folders
コメントの関数名・構造体名がここ以外にもちょくちょく間違ってるので直しといてください

2020-03-25 05:52 UTC, wtks submitted a review, later dismissed
マージします

2020-03-25 05:52 UTC, wtks commented on event/topic.go
> +	//		clip_folder: model.clipFolder
```suggestion
	//		clip_folder: *model.ClipFolder
```

2020-03-25 05:52 UTC, wtks commented on event/topic.go
> +	//		old_clip_folder: model.clipFolder
```suggestion
	//		old_clip_folder: *model.ClipFolder
```

2020-03-25 05:52 UTC, wtks commented on event/topic.go
> +	//		clip_folder: model.clipFolder
```suggestion
	//		clip_folder: *model.ClipFolder
```

2020-03-25 05:52 UTC, wtks commented on event/topic.go
> +	//		clip_folder: model.clipFolder
```suggestion
	//		clip_folder: *model.ClipFolder
```

2020-03-25 05:52 UTC, wtks commented on event/topic.go
> +	//		clip_folder_message: model.clipFolderMessage
```suggestion
	//		clip_folder_message: *model.ClipFolderMessage
```

2020-03-25 05:52 UTC, wtks commented on event/topic.go
> +	//		clip_folder_message: model.clipFolderMessage
```suggestion
	//		clip_folder_message: *model.ClipFolderMessage
```

2020-03-25 05:53 UTC, wtks approved these changes

2020-03-25 06:00 UTC, merged