通知機構
traPtitech/traQ pull request #86
Opened 2018-02-12 16:44 UTC by wtks

細かいところ以外は完成して、現在masterにあるapiに関する通知は実装しました。
とりあえず一旦masterに取り込んで欲しい。

2018-02-14 02:37 UTC, tohutohu requested changes

2018-02-14 02:37 UTC, tohutohu commented on docs/db_schema.md
> +| token | VARCHAR(255) | NOT NULL PRIMARY KEY | デバイストークン |
ここトークンの種類が必要なくなった理由はなぜですか？

2018-02-14 02:37 UTC, tohutohu commented on docs/db_schema.md
> +| token | VARCHAR(255) | NOT NULL PRIMARY KEY | デバイストークン |
iOSもAndroidもSWもFCMでできるからですかね

2018-02-14 02:37 UTC, tohutohu commented on router/notification.go
> +	userId := c.Get("user").(*model.User).ID
多分govetに通すとIDにしてって言われるので直してほしい

2018-02-14 02:38 UTC, wtks commented on docs/db_schema.md
> +| token | VARCHAR(255) | NOT NULL PRIMARY KEY | デバイストークン |
そうです

2018-02-14 02:42 UTC, wtks commented on router/notification.go
> +	userId := c.Get("user").(*model.User).ID
言われませんでしたね・・・

2018-02-14 23:47 UTC, tohutohu commented on router/notification.go
> +	userId := c.Get("user").(*model.User).ID
どちらにせよ全部(Goのコード側は)IDで統一してるのでしてほしさある

2018-02-15 03:10 UTC, wtks commented on router/notification.go
> +	userId := c.Get("user").(*model.User).ID
直した

2018-02-15 14:07 UTC, tohutohu approved these changes

2018-02-15 14:07 UTC, merged