OGPクローラ
traPtitech/traQ pull request #941
Opened 2020-06-16 12:49 UTC by spaspa

リクエストのあったURLに対しOGP情報をクロールし、それらを1週間キャッシュします。

- JSの実行には対応していないため、取得できるOGP情報に限りがあります
- canonical URLがキーになっているわけではないため、非canonicalなURLに対するキャッシュが保管されます

#ref. 582

2020-06-16 13:19 UTC, wtks requested changes
あとネガティブキャッシュ(40xエラーとか)も入れたいですね。

2020-06-16 13:19 UTC, wtks commented on migration/current.go
> +		v20(), // OGPキャッシュ追加
今のmasterには既にv20が存在してるから、リベースしてv21にしてください

2020-06-16 13:19 UTC, wtks commented on model/ogp.go
> +	URL       string    `gorm:"type:text;not null"`
URLのインデックスが効かないのはまずいので、sha1とかでハッシュしたものも載せて、sqlのwhereの条件でハッシュとurlの両方を完全一致で指定する感じにしたい

2020-06-16 13:19 UTC, wtks commented on service/ogp/parser_test.go
> +func TestParseDoc(t *testing.T) {
競合しないようなテストは`t.Parallel()`で並列実行させると良さ

2020-06-16 13:19 UTC, wtks commented on service/ogp/formatter.go
> +func MergeDefaultPageMetaAndOpenGraph(og *opengraph.OpenGraph, meta *DefaultPageMeta) model.Ogp {
ポインタで返したほうがいいかなあ

2020-06-16 13:19 UTC, wtks commented on service/ogp/parser.go
> +	defer resp.Body.Close()
これはresp.StatusCodeの比較より前にに書く必要がありますね

2020-06-28 02:53 UTC, wtks commented on repository/ogp_cache_impl.go
> +	_, err := hash.Write([]byte(url))
これはcrypto/sha1の実装見ないと分からないことだけど、sha1のWriteは必ずerrがnilなので無視して大丈夫です（但し、`_, _ = hash...`で明示的に無視しないとLintに怒られる)

2020-06-28 02:53 UTC, wtks commented on repository/ogp_cache.go
> +	CreateOgpCache(url string, content model.Ogp) (c *model.OgpCache, err error)
model.Ogpのポインタを引数に取るようにして、nilだったらnegative扱いにするとCreateOgpCacheNegativeと共通化できそう

2020-06-28 02:53 UTC, wtks commented on docs/v3-api.yaml
> +          description: 指定したURLが不正か、指定されたURLに対するOGP情報が存在しませんでした。
OGPが存在しないのは404な気がする

2020-06-28 02:53 UTC, wtks commented on service/ogp/parser.go
> +	resp, err := http.Get(url.String())
グローバルなhttpクライアントはタイムアウト時間が無限(未設定)なので、
https://github.com/traPtitech/traQ/blob/3e6d723b99a7fb814cb6f2bcdbd25c0055dc5926/service/bot/event/dispatcher_impl.go#L37
みたいにhttp.Clientを新たに作ってあげる必要があります

2020-06-28 02:53 UTC, wtks commented on router/v3/ogp.go
> +func (h *Handlers) GetOgp(c echo.Context) error {
`c.Response().Header().Set(consts.HeaderCacheControl, "public, max-age=604800")`でAPIクライアント側にもキャッシュさせよう

2020-06-28 02:53 UTC, wtks commented on router/v3/ogp.go
> +		return herror.BadRequest(err)
ここに`html.Parse`のエラーや、存在しないドメインへのリクエスト時の名前解決失敗・タイムアウトのエラーも流れてくると思うけど、そのときもネガティブキャッシュしたほうがいいかな

2020-06-28 04:16 UTC, spaspa commented on router/v3/ogp.go
> +		return herror.BadRequest(err)
名前解決失敗とかのエラーって404になるのかな？本来ステータスコードで管理されない部分が出てきて面倒だからBad Requestでいいかなぁとか思ってた

2020-06-28 05:07 UTC, wtks commented on router/v3/ogp.go
> +		return herror.BadRequest(err)
名前解決失敗は殆どの場合は、ドメインが存在しないことだから、404 NotFoundじゃない？
どっちかというと、`html.Parse`が出来ないものをキャッシュしていないのが気になってて、現状の実装だとhtml以外のURL(json, 画像, 動画などなど)が来たときに、ogpがnullであることをキャッシュしてないから毎回アクセス仕掛けることになってしまう。

2020-06-28 05:25 UTC, wtks commented
traQクライアントがメッセージをWSで受信→メッセージ内のURLのOGPを自動取得しに行く
って感じだったら、同じURLのOGP取得APIが複数のオンラインの端末から一斉に何十件も叩かれる可能性があって、その時キャッシュが存在していないURLのOGPの取得だった場合に、そのURLに同時に何十リクエストも飛んでしまうことになってしまうから、singleflightでキャッシュ確認・OGP更新or取得処理を丸ごと囲ったほうがいいかもしれない

2020-06-30 12:46 UTC, spaspa commented on router/v3/ogp.go
> +		return herror.BadRequest(err)
あーなるほど、URLとして有効でもHTMLじゃない場合はキャッシュしておかないと危ないか、:kansya:

2020-06-30 14:41 UTC, wtks commented on router/v3/ogp.go
> +	var group singleflight.Group
singleflight.GroupはGetOgpの呼び出し間で共有する必要があります。
Handlers構造体のフィールドの一つとして追加してもらってOK

2020-06-30 14:41 UTC, wtks commented on router/v3/ogp.go
> +			c.Response().Header().Set(consts.HeaderCacheControl, fmt.Sprintf("public, max-age=%d", cacheDuration))
echoのコンテキストはリクエスト間で共有できないので、Doの内部では使えません。(処理が共有された場合は、最初に発火させたリクエストのコンテキストでのみDoの関数が呼び出される)
ので、レスポンスヘッダのセットはDoの外に引き剥がす必要があります。

2020-06-30 14:48 UTC, wtks commented on docs/v3-api.yaml
> +            - 'null'
typeでnull指定じゃなくて、`nullable: true`で指定したほうがいいかもしれない。
あと、nullableじゃないフィールドは、objectのrequiredでも指定しないとnode-traqでOptionalな型になってしまうみたいです

2020-07-02 08:36 UTC, spaspa reviewed
singleflight周り修正してローカルでは動いたんですがこれで大丈夫かどうか怪しいので見てもらえると:pray:
lintなどはもうしばらくあとで修正します

2020-07-03 01:12 UTC, wtks commented on router/v3/router.go
> +	"github.com/golang/groupcache/singleflight"
`golang.org/x/sync/singleflight`の方を使ってください

2020-07-03 01:12 UTC, wtks commented on service/ogp/url_normalizer.go
> +package ogp
ファイルを削除しといてください

2020-07-03 02:39 UTC, wtks reviewed
`go mod tidy`で`go.mod`を綺麗にしといてください

2020-07-03 02:39 UTC, wtks commented on docs/v3-api.yaml
> +        imags:
```suggestion
        images:
```

2020-07-03 16:31 UTC, wtks approved these changes

2020-07-03 16:31 UTC, merged