メッセージ検索
traPtitech/traQ pull request #946
Opened 2020-06-19 15:43 UTC by FujishigeTemma

2020-06-19 16:03 UTC, FujishigeTemma commented
今、動くのword, to, fromだけです。after, beforeはrangeQueryが動いてないんで直します🙏
https://md.trap.jp/xzcB0DuaTgipN2iqaKe6bw

2020-06-20 00:45 UTC, wtks requested changes

2020-06-20 00:45 UTC, wtks commented on service/search/engine.go
> +func GetSearchQuery(c echo.Context) *Query {
この処理はAPI router特有(echo.Context)の検索実行の入力引数の準備にあたるので、routerパッケージ側でして欲しいです

2020-06-20 00:45 UTC, wtks commented on service/search/engine.go
> +func GetSearchQuery(c echo.Context) *Query {
ちなみに、QueryParamで手動で一生懸命取り出さなくても、jsonのリクエストと同じように構造体にバインドできます
https://github.com/traPtitech/traQ/blob/2a38721a5130b14d3c054f22ec1814d0095e2f98/router/v3/utils.go#L105

2020-06-20 00:45 UTC, wtks commented on service/search/engine.go
> +type Query struct {
https://github.com/traPtitech/traQ/tree/master/utils/optional パッケージに入ってる型を使うといいと思う

2020-06-20 00:45 UTC, wtks commented on service/search/es.go
> +		musts = append(musts, elastic.NewMatchQuery("text", q.To)) // keywordでindexに追加するほうがいいかもしれない(投稿時しかつかないし)
> keywordでindexに追加するほうがいいかもしれない

僕もそう思う

2020-06-20 00:45 UTC, wtks commented on service/search/es.go
> +		musts = append(musts, elastic.NewMatchQuery("text", q.Cite))
citeもkeywordでindexに追加でいいと思う

2020-07-08 03:02 UTC, wtks commented on cmd/config.go
> +	engine.DB().SetConnMaxLifetime(time.Duration(c.MariaDB.Connection.LifeTime) * time.Second)
312,313,314行目でも二重になっちゃってるんでこっちは削除で

2020-07-08 03:08 UTC, wtks commented on service/search/es.go
> +		musts = append(musts, elastic.NewRangeQuery("createdAt").Gte(q.After.NullTime.Time.Format("2006-01-02T15:04:05Z")).Lte(q.Before.NullTime.Time.Format("2006-01-02T15:04:05Z")))
.NullTime.Timeは.ValueOrZero()と書けます(あんまり変わらんけど)

2020-07-08 03:16 UTC, wtks commented on service/search/es.go
> +					"format": "strict_date_time_no_millis", // 2006-01-02T15:04:05Z
es7.8.0にあげると、`strict_date_optional_time_nanos`フォーマットが使えるらしい
https://www.elastic.co/guide/en/elasticsearch/reference/7.8/mapping-date-format.html

2021-02-06 09:11 UTC, motoki317 commented
メッセージの新規投稿/編集/削除は現在の実装で動いてそうなんですが、起動時に既にあるメッセージでesにindexされていないものを取り込むのはどうするのが良いかなと考えていました

`elasticsearch mariadb sync`みたいに適当に調べると、DBからesへの同期はlogstashとJDBCプラグインで可能というのが出てくるんですが、今はtraQアプリ側でメッセージをparseしたりしていくつかフィールドを追加しているので、これができるかが未検証（できても面倒そう）

もしくは、どこかにes_last_insert_valueみたいな値を持っておいて（DB?）、traQアプリ側でsyncするのが良いのかなと
実装をtraQアプリ側で完結させるならこれだけど、syncしてるときは多分blockingしないといけないし（メッセージの編集とかが来たときにバグりそう）、少し重そう

2021-02-07 02:03 UTC, wtks commented
esへの同期は結果整合性があればいい(マスターデータであるmariadbと即座に同期できなくてもいい)と思ってるので、同期待ちキューみたいなの用意して、同期中に過去メッセージが編集されたらそこに突っ込んで後で更新すればいいんじゃないかなと思ってる

2021-02-07 02:14 UTC, wtks commented
あと前にも言ったかもしれないけど、当初はほぼESが使ってみたかったという理由だけでESで実装しはじめて、今では使っても使わなくてもええわって気分なので、検索エンジンのインターフェイスの抽象化が出来てれば、es使わない方法で検索実装しても別に構わないです。完全におまかせします

2021-02-08 03:00 UTC, motoki317 commented
即時同期をやめて、定期的に(とりあえず1分ごとに)同期するようにしてみました

2021-02-08 11:34 UTC, motoki317 commented
`messages`テーブルってdmのメッセージも一緒に入ってるんだった...

2021-02-09 07:01 UTC, motoki317 commented
- メッセージについているスタンプの検索
- word以外の高度な検索（and, or, not, should）
- 開発用データセット
- テスト

ができてませんが、それ以外はだいたい終わったはずです

2021-02-09 11:30 UTC, wtks approved these changes, later dismissed
N+1が存在してるのは分かってるけど、とりあえず機能の実装としては良さそうだから一旦マージしてチューニングしていく感じかな
ステージングに環境用意したい

2021-02-09 11:53 UTC, motoki317 commented
そんな感じに思っていました
正直、traQ（本番）のメッセージ量をESが食うのにメモリとかが十分かがまだ分かってないので、そこを調べるのが一番のTODOです

2021-02-12 01:39 UTC, motoki317 commented
実データをindexしてみたところ、bot除外が欲しいことに気づいたので追加しました ><

その際に、最初にindexする時のみとは言え、ユーザーがBotであるかを取得するN+1問題を回避するためにworkaroundを仕込んだりしました
message/channel managerみたいにユーザーをいい感じにmanager, cacheするものって無いですよね

2021-02-12 04:41 UTC, wtks approved these changes

2021-02-12 07:03 UTC, merged